package com.example.geosegalmex.Pecuario.UtilidadesPecuario;

public class UtilidadesPecuario {

    ////////////////////////////////////////////////////////////////////////////

    //Tabla Bovinos Pecuario
    public static final String TABLA_PECUARIO_BOVINOS = "TB_BOVINOPECUARIO";

    public static final String COLUMN_FOLIO_PECUBOVINO = "ID_BOVINO";
    public static final String COLUMN_FOLIOENCUESTA_PECU = "FOLIOENCPECU";
    public static final String COLUMN_TIPORAZA_BOVINO = "RAZABOVINO";
    public static final String COLUMN_RAZAPURA_UPF = "RAZAPURABOVINO";
    public static final String COLUMN_OTRARAZAPURA_UPF = "OTRARAZAPURABOVINO";
    public static final String COLUMN_RAZACRUZA_UPF = "RAZACRUZABOVINO";
    public static final String COLUMN_OTRARAZACRUZA_UPF = "OTRARAZACRUZABOVINO";

    public static final String CREAR_TABLA_PECUARIOBOVINOS = "CREATE TABLE " + TABLA_PECUARIO_BOVINOS +
            "(" + COLUMN_FOLIO_PECUBOVINO +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENCUESTA_PECU +
            " VARCHAR, "+ COLUMN_TIPORAZA_BOVINO +
            " VARCHAR, "+ COLUMN_RAZAPURA_UPF +
            " VARCHAR, "+ COLUMN_OTRARAZAPURA_UPF +
            " VARCHAR, "+ COLUMN_RAZACRUZA_UPF +
            " VARCHAR, "+ COLUMN_OTRARAZACRUZA_UPF +
            " VARCHAR); ";





    ///////////////////////////////////////////////////////////////////////////

    //Tabla Ovinos Pecuario
    public static final String TABLA_PECUARIO_OVINOS = "TB_OVINOPECUARIO";

    public static final String COLUMN_FOLIO_PECUOVINO = "ID_BOVINO";
    public static final String COLUMN_FOLIOENC_PECU = "FOLIOENCPECUO";
    public static final String COLUMN_TIPORAZA_OVINO_PRED = "RAZAOVINOPRED";
    public static final String COLUMN_TIPORAZA_OVINO_PRED_OTRO = "RAZAOVINOTROPRED";





    //Crear la tabla Ovino pecuario
    public static final String CREAR_TABLA_PECUARIOOVINOS = "CREATE TABLE " + TABLA_PECUARIO_OVINOS +
            "(" + COLUMN_FOLIO_PECUOVINO +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENC_PECU +
            " VARCHAR, "+ COLUMN_TIPORAZA_OVINO_PRED +
            " VARCHAR, "+ COLUMN_TIPORAZA_OVINO_PRED_OTRO +
            " VARCHAR); ";





    /////////////////////////////////////////////////////////////////////////////////////////////////

    //Tabla CAPRINOS Pecuario
    public static final String TABLA_PECUARIO_CAPRINOS = "TB_CAPRINOPECUARIO";

    public static final String COLUMN_FOLIO_PECUCAPRINO = "ID_CAPRINO";
    public static final String COLUMN_FOLIOENC_PECUCAPRI = "FOLIOENCPECUCAP";
    public static final String COLUMN_TIPORAZA_CAPRINO_PRED = "RAZACAPPRED";
    public static final String COLUMN_TIPORAZA_CAPRINO_PRED_OTRO = "RAZACAPOTROPRED";





    //Crear la tabla CAPRINO pecuario
    public static final String CREAR_TABLA_PECUARIOCAPRINOS = "CREATE TABLE " + TABLA_PECUARIO_CAPRINOS +
            "(" + COLUMN_FOLIO_PECUCAPRINO +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENC_PECUCAPRI +
            " VARCHAR, "+ COLUMN_TIPORAZA_CAPRINO_PRED +
            " VARCHAR, "+ COLUMN_TIPORAZA_CAPRINO_PRED_OTRO +
            " VARCHAR); ";




    //////////////////////////////////////////////////////////////////////////////////

    //Tabla Pecuario estructura del hato
    public static final String TABLA_PECUARIO_ESTRUCTURAHATO = "TB_PECUESTRUCTURAHATO";

    public static final String COLUMN_FOLIO_PECUESTHATO = "ID_ESTRUCTHATO";
    public static final String COLUMN_FOLIOENCUESTA_HATO = "FOLIOENCPECUHATO";

    public static final String COLUMN_BOVSEMENTALES = "BOVSEMENTALES";
    public static final String COLUMN_BOVSEMCANTIDADCAB = "BOVSEMCANTIDADCAB";
    public static final String COLUMN_BOVSEMPRECIOCAB = "BOVSEMPRECIOCAB";

    public static final String COLUMN_BOVVIENTADULTAS = "BOVVIENTADULTAS";
    public static final String COLUMN_BOVVIENTADULTACANTCAB = "BOVVIENTADULTACANTCAB";
    public static final String COLUMN_BOVVIENTADULTAPRECIO = "BOVVIENTADULTAPRECIO";

    public static final String COLUMN_BOVVAQUILLAS = "BOVVAQUILLAS";
    public static final String COLUMN_BOVVAQUILLASCANTCAB = "BOVVAQUILLASCANTCAB";
    public static final String COLUMN_BOVVAQUILLASPRECIO = "BOVVAQUILLASPRECIO";

    public static final String COLUMN_BOVVIENTDESARROLLO = "BOVVIENTDESARROLLO";
    public static final String COLUMN_BOVVIENTDESARROLLOCANTCAB = "BOVVIENTDESARROLLOCANTCAB";
    public static final String COLUMN_BOVVIENTDESARROLLOPRECIO = "BOVVIENTDESARROLLOPRECIO";

    public static final String COLUMN_BOVBECERROS = "BOVBECERROS";
    public static final String COLUMN_BOVBECERROSCANTCAB = "BOVBECERROSCANTCAB";
    public static final String COLUMN_BOVBECERROSPRECIO = "BOVBECERROSPRECIO";

    public static final String COLUMN_BOVTORETESDES = "BOVTORETESDES";
    public static final String COLUMN_BOVTORETESDESCANTCAB = "BOVTORETESDESCANTCAB";
    public static final String COLUMN_BOVTORETESDESPRECIO = "BOVTORETESDESPRECIO";

    public static final String COLUMN_BOVTORETESFINAL = "BOVTORETESFINAL";
    public static final String COLUMN_BOVTORETESFINALCANTCAB = "BOVTORETESFINALCANTCAB";
    public static final String COLUMN_BOVTORETESFINALPRECIO = "BOVTORETESFINALPRECIO";


    //Crear la tabla estructura del hato
    public static final String CREAR_TABLA_PECUESTRUCTURAHATO = "CREATE TABLE " + TABLA_PECUARIO_ESTRUCTURAHATO +
            "(" + COLUMN_FOLIO_PECUESTHATO +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENCUESTA_HATO +
            " VARCHAR, "+ COLUMN_BOVSEMENTALES +
            " VARCHAR, "+ COLUMN_BOVSEMCANTIDADCAB +
            " VARCHAR, "+ COLUMN_BOVSEMPRECIOCAB +
            " VARCHAR, "+ COLUMN_BOVVIENTADULTAS +
            " VARCHAR, "+ COLUMN_BOVVIENTADULTACANTCAB +
            " VARCHAR, "+ COLUMN_BOVVIENTADULTAPRECIO +
            " VARCHAR, "+ COLUMN_BOVVAQUILLAS +
            " VARCHAR, "+ COLUMN_BOVVAQUILLASCANTCAB +
            " VARCHAR, "+ COLUMN_BOVVAQUILLASPRECIO +
            " VARCHAR, "+ COLUMN_BOVVIENTDESARROLLO +
            " VARCHAR, "+ COLUMN_BOVVIENTDESARROLLOCANTCAB +
            " VARCHAR, "+ COLUMN_BOVVIENTDESARROLLOPRECIO +
            " VARCHAR, "+ COLUMN_BOVBECERROS +
            " VARCHAR, "+ COLUMN_BOVBECERROSCANTCAB +
            " VARCHAR, "+ COLUMN_BOVBECERROSPRECIO +
            " VARCHAR, "+ COLUMN_BOVTORETESDES +
            " VARCHAR, "+ COLUMN_BOVTORETESDESCANTCAB +
            " VARCHAR, "+ COLUMN_BOVTORETESDESPRECIO +
            " VARCHAR, "+ COLUMN_BOVTORETESFINAL +
            " VARCHAR, "+ COLUMN_BOVTORETESFINALCANTCAB +
            " VARCHAR, "+ COLUMN_BOVTORETESFINALPRECIO +
            " VARCHAR); ";





    //////////////////////////////////////////////////////////////////////////////////

    //Tabla Pecuario inventario ganado bovino leche
    public static final String TABLA_PECUARIO_BOVINOLECHE = "TB_PECUBOVINOLECHE";

    public static final String COLUMN_FOLIO_PECUINVBOVLEC = "ID_PECUINVBOVLEC";
    public static final String COLUMN_FOLIOENCUESTA_BOVLEC = "FOLIOENCPECUINVBOVLEC";

    public static final String COLUMN_BOVSEMENTALLEC = "BOVSEMENTALLEC";
    public static final String COLUMN_BOVSEMCANTIDADCABLEC = "BOVSEMCANTIDADCABLEC";
    public static final String COLUMN_BOVSEMPRECIOCABLEC = "BOVSEMPRECIOCABLEC";

    public static final String COLUMN_BOVVACAPRODLEC = "BOVVACAPRODLEC";
    public static final String COLUMN_BOVVACACANTIDADCABLEC = "BOVVACACANTIDADCABLEC";
    public static final String COLUMN_BOVVACAPRECIOCABLEC = "BOVVACAPRECIOCABLEC";

    public static final String COLUMN_BOVVASEPRODLEC = "BOVVASEPRODLEC";
    public static final String COLUMN_BOVVASECANTIDADCABLEC = "BOVVASECANTIDADCABLEC";
    public static final String COLUMN_BOVVASEPRECIOCABLEC = "BOVVASEPRECIOCABLEC";

    public static final String COLUMN_BOVVAQPRODLEC = "BOVVAQPRODLEC";
    public static final String COLUMN_BOVVAQCANTIDADCABLEC = "BOVVAQCANTIDADCABLEC";
    public static final String COLUMN_BOVVAQPRECIOCABLEC = "BOVVAQPRECIOCABLEC";

    public static final String COLUMN_BOVHEMDESPRODLEC = "BOVHEMDESPRODLEC";
    public static final String COLUMN_BOVHEMDESCANTIDADCABLEC = "BOVBECERROSCANTCAB";
    public static final String COLUMN_BOVHEMDESPRECIOCABLEC = "BOVBECERROSPRECIO";

    public static final String COLUMN_BOVBECPRODLEC = "BOVTORETESDES";
    public static final String COLUMN_BOVBECCANTIDADCABLEC = "BOVBECCANTIDADCABLEC";
    public static final String COLUMN_BOVBECPRECIOCABLEC = "BOVBECPRECIOCABLEC";

    public static final String COLUMN_BOVBECERRASPRODLEC = "BOVBECERRASPRODLEC";
    public static final String COLUMN_BOVBECERRASCANTIDADCABLEC = "BOVBECERRASCANTIDADCABLEC";
    public static final String COLUMN_BOVBECERRASPRECIOCABLEC = "BOVBECERRASPRECIOCABLEC";

    public static final String COLUMN_BOVTORETESPRODLEC = "BOVTORETESPRODLEC";
    public static final String COLUMN_BOVTORETESCANTIDADCABLEC = "BOVTORETESCANTIDADCABLEC";
    public static final String COLUMN_BOVTORETESPRECIOCABLEC = "BOVTORETESPRECIOCABLEC";


    //Crear la tabla inventario ganado bovino leche
    public static final String CREAR_TABLA_PECUBOVINOLECHE = "CREATE TABLE " + TABLA_PECUARIO_BOVINOLECHE +
            "(" + COLUMN_FOLIO_PECUINVBOVLEC +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENCUESTA_BOVLEC +

            " VARCHAR, "+ COLUMN_BOVSEMENTALLEC +
            " VARCHAR, "+ COLUMN_BOVSEMCANTIDADCABLEC +
            " VARCHAR, "+ COLUMN_BOVSEMPRECIOCABLEC +

            " VARCHAR, "+ COLUMN_BOVVACAPRODLEC +
            " VARCHAR, "+ COLUMN_BOVVACACANTIDADCABLEC +
            " VARCHAR, "+ COLUMN_BOVVACAPRECIOCABLEC +

            " VARCHAR, "+ COLUMN_BOVVASEPRODLEC +
            " VARCHAR, "+ COLUMN_BOVVASECANTIDADCABLEC +
            " VARCHAR, "+ COLUMN_BOVVASEPRECIOCABLEC +

            " VARCHAR, "+ COLUMN_BOVVAQPRODLEC +
            " VARCHAR, "+ COLUMN_BOVVAQCANTIDADCABLEC +
            " VARCHAR, "+ COLUMN_BOVVAQPRECIOCABLEC +

            " VARCHAR, "+ COLUMN_BOVHEMDESPRODLEC +
            " VARCHAR, "+ COLUMN_BOVHEMDESCANTIDADCABLEC +
            " VARCHAR, "+ COLUMN_BOVHEMDESPRECIOCABLEC +

            " VARCHAR, "+ COLUMN_BOVBECPRODLEC +
            " VARCHAR, "+ COLUMN_BOVBECCANTIDADCABLEC +
            " VARCHAR, "+ COLUMN_BOVBECPRECIOCABLEC +

            " VARCHAR, "+ COLUMN_BOVBECERRASPRODLEC +
            " VARCHAR, "+ COLUMN_BOVBECERRASCANTIDADCABLEC +
            " VARCHAR, "+ COLUMN_BOVBECERRASPRECIOCABLEC +

            " VARCHAR, "+ COLUMN_BOVTORETESPRODLEC +
            " VARCHAR, "+ COLUMN_BOVTORETESCANTIDADCABLEC +
            " VARCHAR, "+ COLUMN_BOVTORETESPRECIOCABLEC +
            " VARCHAR); ";






    //////////////////////////////////////////////////////////////////////////////////

    //Tabla Pecuario inventario ganado OVINO
    public static final String TABLA_PECUARIO_INVENTARIOGANOVINO = "TB_PECUINVENTARIOGANOVINO";

    public static final String COLUMN_FOLIO_PECUINVGANOVI = "ID_PECUINVGANOVI";
    public static final String COLUMN_FOLIOENCUESTA_PECUOVI = "FOLIOENCPECUINVOVI";

    public static final String COLUMN_OVINOSEMENTAL = "OVINOSEMENTAL";
    public static final String COLUMN_OVISEMCANTIDAD = "OVISEMCANTIDAD";
    public static final String COLUMN_OVISEMEPRECIO = "OVISEMEPRECIO";

    public static final String COLUMN_OVIBORREGADUL = "OVIBORREGADUL";
    public static final String COLUMN_OVIBORREGADULCANTIDAD = "OVIBORREGADULCANTIDAD";
    public static final String COLUMN_OVIBORREGADULPRECIO = "OVIBORREGADULPRECIO";

    public static final String COLUMN_OVIPRIMALASPROD = "OVIPRIMALASPROD";
    public static final String COLUMN_OVIPRIMALASCANTIDAD = "OVIPRIMALASCANTIDAD";
    public static final String COLUMN_OVIPRIMALASPRECIO = "OVIPRIMALASPRECIO";

    public static final String COLUMN_OVICORDERAS = "OVICORDERAS";
    public static final String COLUMN_OVICORDERASCANTIDAD = "OVICORDERASCANTIDAD";
    public static final String COLUMN_OVICORDERASPRECIO = "OVICORDERASPRECIO";

    public static final String COLUMN_OVICORDEROSLACT = "OVICORDEROSLACT";
    public static final String COLUMN_OVICORDEROSLACTCANTIDAD = "OVICORDEROSLACTCANTIDAD";
    public static final String COLUMN_OVICORDEROSLACTPRECIO = "OVICORDEROSLACTPRECIO";

    public static final String COLUMN_OVICORDEROSENG = "OVICORDEROSENG";
    public static final String COLUMN_OVICORDEROSENGCANTIDAD = "OVICORDEROSENGCANTIDAD";
    public static final String COLUMN_OVICORDEROSENGPRECIO = "OVICORDEROSENGPRECIO";


    //Crear la tabla inventario ganado ovino
    public static final String CREAR_TABLA_PECUINVGANOVINO = "CREATE TABLE " + TABLA_PECUARIO_INVENTARIOGANOVINO +
            "(" + COLUMN_FOLIO_PECUINVGANOVI +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENCUESTA_PECUOVI +

            " VARCHAR, "+ COLUMN_OVINOSEMENTAL +
            " VARCHAR, "+ COLUMN_OVISEMCANTIDAD +
            " VARCHAR, "+ COLUMN_OVISEMEPRECIO +

            " VARCHAR, "+ COLUMN_OVIBORREGADUL +
            " VARCHAR, "+ COLUMN_OVIBORREGADULCANTIDAD +
            " VARCHAR, "+ COLUMN_OVIBORREGADULPRECIO +

            " VARCHAR, "+ COLUMN_OVIPRIMALASPROD +
            " VARCHAR, "+ COLUMN_OVIPRIMALASCANTIDAD +
            " VARCHAR, "+ COLUMN_OVIPRIMALASPRECIO +

            " VARCHAR, "+ COLUMN_OVICORDERAS +
            " VARCHAR, "+ COLUMN_OVICORDERASCANTIDAD +
            " VARCHAR, "+ COLUMN_OVICORDERASPRECIO +

            " VARCHAR, "+ COLUMN_OVICORDEROSLACT +
            " VARCHAR, "+ COLUMN_OVICORDEROSLACTCANTIDAD +
            " VARCHAR, "+ COLUMN_OVICORDEROSLACTPRECIO +

            " VARCHAR, "+ COLUMN_OVICORDEROSENG +
            " VARCHAR, "+ COLUMN_OVICORDEROSENGCANTIDAD +
            " VARCHAR, "+ COLUMN_OVICORDEROSENGPRECIO +
            " VARCHAR); ";







    //////////////////////////////////////////////////////////////////////////////////

    //Tabla Pecuario inventario ganado CAPRINO
    public static final String TABLA_PECUARIO_INVENTARIOGANCAPRI = "TB_PECUINVENTARIOGANCAPRINO";

    public static final String COLUMN_FOLIO_PECUINVGANCAPRI = "ID_PECUINVGANCAPRI";
    public static final String COLUMN_FOLIOENCUESTA_PECUCAPRI = "FOLIOENCPECUINVOVI";

    public static final String COLUMN_CAPRINOSEMENTAL = "CAPRINOSEMENTAL";
    public static final String COLUMN_CAPRISEMCANTIDAD = "CAPRISEMCANTIDAD";
    public static final String COLUMN_CAPRISEMEPRECIO = "CAPRISEMEPRECIO";

   // public static final String COLUMN_CAPRINOSCABRASLACTACION = "CAPRINOSCABRASLACTACION";
   // public static final String COLUMN_CAPRICABRASLACTCANTIDAD = "CAPRICABRASLACTCANTIDAD";
   // public static final String COLUMN_CAPRICABRASLACTPRECIO = "CAPRICABRASLACTPRECIO";

    public static final String COLUMN_CAPRINOCABRASSECAS = "CAPRINOCABRASSECAS";
    public static final String COLUMN_CAPRICABRASSECCANTIDAD = "CAPRICABRASSECCANTIDAD";
    public static final String COLUMN_CAPRICABRASSECPRECIO = "CAPRICABRASSECPRECIO";

    public static final String COLUMN_CAPRINOCABRASSERVPRIMERPARTO = "CAPRINOCABRASSERVPRIMERPARTO";
    public static final String COLUMN_CAPRICABRASPRIMERPARTOCANTIDAD = "CAPRICABRASPRIMERPARTOCANTIDAD";
    public static final String COLUMN_CAPRICABRASPRIMPARTOPRECIO = "CAPRICABRASPRIMPARTOPRECIO";

    public static final String COLUMN_CAPRINOCABRASDESAR = "CAPRINOCABRASDESAR";
    public static final String COLUMN_CAPRINOCABRASDESCANTIDAD = "CAPRINOCABRASDESCANTIDAD";
    public static final String COLUMN_CAPRINOCABRASDESPRECIO = "CAPRINOCABRASDESPRECIO";

    public static final String COLUMN_CAPRICABRASLACTANTES = "CAPRICABRASLACTANTES";
    public static final String COLUMN_CAPRICABRASLATCANTIDAD = "CAPRICABRASLATCANTIDAD";
    public static final String COLUMN_CAPRICABRASLACPRECIO = "CAPRICABRASLACPRECIO";

    public static final String COLUMN_CAPRICABRITOLACTANTES = "CAPRICABRITOLACTANTES";
    public static final String COLUMN_CAPRICABLACTCANTIDAD = "CAPRICABLACTCANTIDAD";
    public static final String COLUMN_CAPRICABLACTPRECIO = "CAPRICABLACTPRECIO";

    public static final String COLUMN_CAPRICABRITOENGORDA = "CAPRICABRITOENGORDA";
    public static final String COLUMN_CAPRICABENGCANTIDAD = "CAPRICABENGCANTIDAD";
    public static final String COLUMN_CAPRICABENGPRECIO = "CAPRICABENGPRECIO";

    public static final String COLUMN_EXPLOTACCAPRINO = "EXPLOTACCAPRINO";


    //Crear la tabla inventario ganado caprino
    public static final String CREAR_TABLA_PECUINVGANCPARINO = "CREATE TABLE " + TABLA_PECUARIO_INVENTARIOGANCAPRI +
            "(" + COLUMN_FOLIO_PECUINVGANCAPRI +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENCUESTA_PECUCAPRI +

            " VARCHAR, "+ COLUMN_CAPRINOSEMENTAL +
            " VARCHAR, "+ COLUMN_CAPRISEMCANTIDAD +
            " VARCHAR, "+ COLUMN_CAPRISEMEPRECIO +

          //  " VARCHAR, "+ COLUMN_CAPRINOSCABRASLACTACION +
           // " VARCHAR, "+ COLUMN_CAPRICABRASLACTCANTIDAD +
           // " VARCHAR, "+ COLUMN_CAPRICABRASLACTPRECIO +

            " VARCHAR, "+ COLUMN_CAPRINOCABRASSECAS +
            " VARCHAR, "+ COLUMN_CAPRICABRASSECCANTIDAD +
            " VARCHAR, "+ COLUMN_CAPRICABRASSECPRECIO +

            " VARCHAR, "+ COLUMN_CAPRINOCABRASSERVPRIMERPARTO +
            " VARCHAR, "+ COLUMN_CAPRICABRASPRIMERPARTOCANTIDAD +
            " VARCHAR, "+ COLUMN_CAPRICABRASPRIMPARTOPRECIO +

            " VARCHAR, "+ COLUMN_CAPRINOCABRASDESAR +
            " VARCHAR, "+ COLUMN_CAPRINOCABRASDESCANTIDAD +
            " VARCHAR, "+ COLUMN_CAPRINOCABRASDESPRECIO +

            " VARCHAR, "+ COLUMN_CAPRICABRASLACTANTES +
            " VARCHAR, "+ COLUMN_CAPRICABRASLATCANTIDAD +
            " VARCHAR, "+ COLUMN_CAPRICABRASLACPRECIO +

            " VARCHAR, "+ COLUMN_CAPRICABRITOLACTANTES +
            " VARCHAR, "+ COLUMN_CAPRICABLACTCANTIDAD +
            " VARCHAR, "+ COLUMN_CAPRICABLACTPRECIO +

            " VARCHAR, "+ COLUMN_CAPRICABRITOENGORDA +
            " VARCHAR, "+ COLUMN_CAPRICABENGCANTIDAD +
            " VARCHAR, "+ COLUMN_CAPRICABENGPRECIO +

            " VARCHAR, "+ COLUMN_EXPLOTACCAPRINO +
            " VARCHAR); ";







    //Tabla Pecuario Pastoreo
    public static final String TABLA_PECUARIO_BOVPASTOREO = "TB_BOVINOPASTOREO";

    public static final String COLUMN_ID_PECUBOVPASTOREO = "ID_PECUPASTOREO";
    public static final String COLUMN_FOLIOENC_PECUBOVPASTOR = "FOLENCPECUBOVPAST";

    public static final String COLUMN_DIEBOVFOPAAGPCRIA = "DIEBOVFOPAAGPCRIA";
    public static final String COLUMN_DIEBOVFOPAAGBEC = "DIEBOVFOPAAGBEC";
    public static final String COLUMN_DIEBOVFOPAAGDES = "DIEBOVFOPAAGDES";
    public static final String COLUMN_DIEBOVFOPAAGFIN = "DIEBOVFOPAAGFIN";
    public static final String COLUMN_DIEBOVFOPAAGCOSTO = "DIEBOVFOPAAGCOSTO";

    public static final String COLUMN_DIEBOVFOPAPRAPCRIA = "DIEBOVFOPAPRAPCRIA";
    public static final String COLUMN_DIEBOVFOPAPRABEC = "DIEBOVFOPAPRABEC";
    public static final String COLUMN_DIEBOVFOPAPRADES = "DIEBOVFOPAPRADES";
    public static final String COLUMN_DIEBOVFOPAPRAFIN = "DIEBOVFOPAPRAFIN";
    public static final String COLUMN_DIEBOVFOPAPRACOSTO = "DIEBOVFOPAPRACOSTO";





    //Crear la tabla pecuario pastoreo
    public static final String CREAR_TABLA_PECUARIO_BOVPASTOREO = "CREATE TABLE " + TABLA_PECUARIO_BOVPASTOREO +
            "(" + COLUMN_ID_PECUBOVPASTOREO +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENC_PECUBOVPASTOR +
            " VARCHAR, "+ COLUMN_DIEBOVFOPAAGPCRIA +
            " VARCHAR, "+ COLUMN_DIEBOVFOPAAGBEC +
            " VARCHAR, "+ COLUMN_DIEBOVFOPAAGDES +
            " VARCHAR, "+ COLUMN_DIEBOVFOPAAGFIN +
            " VARCHAR, "+ COLUMN_DIEBOVFOPAAGCOSTO +

            " VARCHAR, "+ COLUMN_DIEBOVFOPAPRAPCRIA +
            " VARCHAR, "+ COLUMN_DIEBOVFOPAPRABEC +
            " VARCHAR, "+ COLUMN_DIEBOVFOPAPRADES +
            " VARCHAR, "+ COLUMN_DIEBOVFOPAPRAFIN +
            " VARCHAR, "+ COLUMN_DIEBOVFOPAPRACOSTO +
            " VARCHAR); ";






    //Tabla Pecuario Pastoreo -dieta alimentacion
    public static final String TABLA_PECUARIO_BOVALIMGANADO = "TBOVALMGAN";

    public static final String COLUMN_ID_PECUBOVALIMGANADO = "IDBOVALMG";
    public static final String COLUMN_FOLIOENC_PECUBOVALIMGANADO = "FOLPECAG";

    public static final String COLUMN_ALIMGANADO_DIEFORENSPCRIA = "DFOREPCRIA";
    public static final String COLUMN_ALIMGANADO_DIEFORENSBEC = "DFORENSB";
    public static final String COLUMN_ALIMGANADO_DIEFORENSDES = "DFORENSD";
    public static final String COLUMN_ALIMGANADO_DIEFORENSFIN = "DFORENSF";
    public static final String COLUMN_ALIMGANADO_DIEFORENSCOSTO  = "DFORENSCO";

    public static final String COLUMN_ALIMGANADO_DIEFORHENPCRIA = "DFORHPCR";
    public static final String COLUMN_ALIMGANADO_DIEFORHENBEC = "DFORHBEC";
    public static final String COLUMN_ALIMGANADO_DIEFORHENDES = "DFORHDES";
    public static final String COLUMN_ALIMGANADO_DIEFORHENFIN = "DFOREFIN";
    public static final String COLUMN_ALIMGANADO_DIEFORHENCOSTO  = "DFORHCO";

    public static final String COLUMN_ALIMGANADO_DIEFORPACALFPCRIA = "DFORPALFPC";
    public static final String COLUMN_ALIMGANADO_DIEFORPACALFBEC = "DFORPABEC";
    public static final String COLUMN_ALIMGANADO_DIEFORPACALFDES = "DFORPADES";
    public static final String COLUMN_ALIMGANADO_DIEFORPACALFFIN = "DFORPAFIN";
    public static final String COLUMN_ALIMGANADO_DIEFORPACALFCOSTO = "DFORPACO";

    public static final String COLUMN_ALIMGANADO_DIECONCOMPCRIA = "DCONCPC";
    public static final String COLUMN_ALIMGANADO_DIECONCOMBEC = "DCONCBEC";
    public static final String COLUMN_ALIMGANADO_DIECONCOMDES = "DCONCDES";
    public static final String COLUMN_ALIMGANADO_DIECONCOMFIN = "DCONCFIN";
    public static final String COLUMN_ALIMGANADO_DIECONCOMCOSTO = "DCONCCOS";

    public static final String COLUMN_ALIMGANADO_DIECONMAIZPCRIA = "DCONMPCRIA";
    public static final String COLUMN_ALIMGANADO_DIECONMAIZBEC = "DCONMABEC";
    public static final String COLUMN_ALIMGANADO_DIECONMAIZDES = "DCONMADES";
    public static final String COLUMN_ALIMGANADO_DIECONMAIZFIN = "DCONMAFIN";
    public static final String COLUMN_ALIMGANADO_DIECONMAIZCOSTO = "DCONMACOS";

    public static final String COLUMN_ALIMGANADO_DIECONPASTAPCRIA = "DCONPASPC";
    public static final String COLUMN_ALIMGANADO_DIECONPASTABEC = "DCONPASBEC";
    public static final String COLUMN_ALIMGANADO_DIECONPASTADES = "DCONPASDES";
    public static final String COLUMN_ALIMGANADO_DIECONPASTAFIN = "DCONPASFIN";
    public static final String COLUMN_ALIMGANADO_DIECONPASTACOSTO = "DCONPASCOS";

    public static final String COLUMN_ALIMGANADO_DIECONBLOQMINPCRIA = "DCONBMPCR";
    public static final String COLUMN_ALIMGANADO_DIECONBLOQMINBEC = "DCONBMBEC";
    public static final String COLUMN_ALIMGANADO_DIECONBLOQMINDES = "DCONBMDES";
    public static final String COLUMN_ALIMGANADO_DIECONBLOQMINFIN = "DCONBMFIN";
    public static final String COLUMN_ALIMGANADO_DIECONBLOQMINCOSTO = "DCONBMCOS";

    public static final String COLUMN_ALIMGANADO_DIECONMELPCRIA = "DCONMEPCR";
    public static final String COLUMN_ALIMGANADO_DIECONMELBEC = "DCONMEBEC";
    public static final String COLUMN_ALIMGANADO_DIECONMELDES = "DCONMEDES";
    public static final String COLUMN_ALIMGANADO_DIECONMELFIN = "DCONMEFIN";
    public static final String COLUMN_ALIMGANADO_DIECONMELCOSTO = "DCONMECOS";

    public static final String COLUMN_ALIMGANADO_DIECONUREAPCRIA = "DCONUPCRIA";
    public static final String COLUMN_ALIMGANADO_DIECONUREABEC = "DCONUBEC";
    public static final String COLUMN_ALIMGANADO_DIECONUREADES = "DCONUDES";
    public static final String COLUMN_ALIMGANADO_DIECONUREAFIN = "DCONUFIN";
    public static final String COLUMN_ALIMGANADO_DIECONUREACOSTO = "DCONUCOS";

    public static final String COLUMN_ALIMGANADO_DIECONVITAMPCRIA = "DCONVPCRIA";
    public static final String COLUMN_ALIMGANADO_DIECONVITAMBEC = "DCONVBEC";
    public static final String COLUMN_ALIMGANADO_DIECONVITAMDES = "DCONVDES";
    public static final String COLUMN_ALIMGANADO_DIECONVITAMFIN = "DCONVFIN";
    public static final String COLUMN_ALIMGANADO_DIECONVITAMCOSTO = "DCONVCOS";

    public static final String COLUMN_ALIMGANADO_DIECONSUBPPCRIA = "DCONSPCRIA";
    public static final String COLUMN_ALIMGANADO_DIECONSUBPBEC = "DCONSBEC";
    public static final String COLUMN_ALIMGANADO_DIECONSUBPDES = "DCONSDES";
    public static final String COLUMN_ALIMGANADO_DIECONSUBPFIN = "DCONSFIN";
    public static final String COLUMN_ALIMGANADO_DIECONSUBPCOSTO = "DCONSCOS";


    //Crear la tabla pecuario pastoreo
    public static final String CREAR_TABLA_PECUARIO_BOVALIMGANADO = "CREATE TABLE " + TABLA_PECUARIO_BOVALIMGANADO +
            "(" + COLUMN_ID_PECUBOVALIMGANADO +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENC_PECUBOVALIMGANADO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORENSPCRIA +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORENSBEC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORENSDES +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORENSFIN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORENSCOSTO +

            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORHENPCRIA +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORHENBEC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORHENDES +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORHENFIN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORHENCOSTO +

            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORPACALFPCRIA +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORPACALFBEC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORPACALFDES +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORPACALFFIN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIEFORPACALFCOSTO +

            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONCOMPCRIA +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONCOMBEC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONCOMDES +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONCOMFIN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONCOMCOSTO +

            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONMAIZPCRIA +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONMAIZBEC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONMAIZDES +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONMAIZFIN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONMAIZCOSTO +

            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONPASTAPCRIA +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONPASTABEC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONPASTADES +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONPASTAFIN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONPASTACOSTO +

            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONBLOQMINPCRIA +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONBLOQMINBEC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONBLOQMINDES +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONBLOQMINFIN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONBLOQMINCOSTO +

            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONMELPCRIA +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONMELBEC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONMELDES +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONMELFIN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONMELCOSTO +

            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONUREAPCRIA +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONUREABEC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONUREADES +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONUREAFIN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONUREACOSTO +

            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONVITAMPCRIA +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONVITAMBEC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONVITAMDES +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONVITAMFIN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONVITAMCOSTO +

            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONSUBPPCRIA +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONSUBPBEC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONSUBPDES +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONSUBPFIN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_DIECONSUBPCOSTO +
            " VARCHAR); ";



    //Tabla Pecuario Pastoreo -composicion dieta ovinos
    public static final String TABLA_PECUARIO_DIETAOVICAPRI = "TBDIOVCA";

    public static final String COLUMN_ID_PECUDIETAOVICAPRI = "IDDIOVCA";
    public static final String COLUMN_FOLIOENC_PECUDIETAOVICAPRI = "FOPEDOVCA";

    public static final String COLUMN_ALIMGANADO_PASTAGOSTENE = "PAAGOEN";
    public static final String COLUMN_ALIMGANADO_PASTAGOSTFEB = "PAAGOFE";
    public static final String COLUMN_ALIMGANADO_PASTAGOSTMAR = "PAAGOMAR";
    public static final String COLUMN_ALIMGANADO_PASTAGOSTABR = "PAAGOAB";
    public static final String COLUMN_ALIMGANADO_PASTAGOSTMAY  = "PAAGOMAY";
    public static final String COLUMN_ALIMGANADO_PASTAGOSTJUN = "PAAGOJUN";
    public static final String COLUMN_ALIMGANADO_PASTAGOSTJUL = "PAAGOJUL";
    public static final String COLUMN_ALIMGANADO_PASTAGOSTAGO = "PAAGOAG";
    public static final String COLUMN_ALIMGANADO_PASTAGOSTSEP = "PAAGOSE";
    public static final String COLUMN_ALIMGANADO_PASTAGOSTOCT  = "PAAGOOC";
    public static final String COLUMN_ALIMGANADO_PASTAGOSTNOV = "PAAGOSNO";
    public static final String COLUMN_ALIMGANADO_PASTAGOSTDIC = "PAAGODI";
    public static final String COLUMN_ALIMGANADO_PASTAGOSTCOS = "PAAGOCO";

    public static final String COLUMN_ALIMGANADO_PASTPRADENE = "PASTPRADENE";
    public static final String COLUMN_ALIMGANADO_PASTPRADFEB = "PASTPRADFEB";
    public static final String COLUMN_ALIMGANADO_PASTPRADMAR = "PASTPRADMAR";
    public static final String COLUMN_ALIMGANADO_PASTPRADABR = "PASTPRADABR";
    public static final String COLUMN_ALIMGANADO_PASTPRADMAY = "PASTPRADMAY";
    public static final String COLUMN_ALIMGANADO_PASTPRADJUN = "PASTPRADJUN";
    public static final String COLUMN_ALIMGANADO_PASTPRADJUL = "PASTPRADJUL";
    public static final String COLUMN_ALIMGANADO_PASTPRADAGO = "PASTPRADAGO";
    public static final String COLUMN_ALIMGANADO_PASTPRADSEP = "PASTPRADSEP";
    public static final String COLUMN_ALIMGANADO_PASTPRADOCT = "PASTPRADOCT";
    public static final String COLUMN_ALIMGANADO_PASTPRADNOV = "PASTPRADNOV";
    public static final String COLUMN_ALIMGANADO_PASTPRADDIC = "PASTPRADDIC";
    public static final String COLUMN_ALIMGANADO_PASTPRADCOS = "PASTPRADCOS";

    public static final String COLUMN_ALIMGANADO_PASTRASTROENE= "PARAENE";
    public static final String COLUMN_ALIMGANADO_PASTRASTROFEB = "PARAFEB";
    public static final String COLUMN_ALIMGANADO_PASTRASTROMAR = "PARAMAR";
    public static final String COLUMN_ALIMGANADO_PASTRASTROABR = "PARAABR";
    public static final String COLUMN_ALIMGANADO_PASTRASTROMAY  = "PARAMAY";
    public static final String COLUMN_ALIMGANADO_PASTRASTROJUN = "PARAJUN";
    public static final String COLUMN_ALIMGANADO_PASTRASTROJUL = "PARAJUL";
    public static final String COLUMN_ALIMGANADO_PASTRASTROAGO = "PARAAGO";
    public static final String COLUMN_ALIMGANADO_PASTRASTROSEP = "PARASEP";
    public static final String COLUMN_ALIMGANADO_PASTRASTROOCT  = "PASTRASTROOCT";
    public static final String COLUMN_ALIMGANADO_PASTRASTRONOV = "PASTRASTRONOV";
    public static final String COLUMN_ALIMGANADO_PASTRASTRODIC = "PASTRASTRODIC";
    public static final String COLUMN_ALIMGANADO_PASTRASTROCOS = "PASTRASTROCOS";

    public static final String COLUMN_ALIMGANADO_PASTCORVERENE = "PASTCORVERENE";
    public static final String COLUMN_ALIMGANADO_PASTCORVERFEB = "PASTCORVERFEB";
    public static final String COLUMN_ALIMGANADO_PASTCORVERMAR = "PASTCORVERMAR";
    public static final String COLUMN_ALIMGANADO_PASTCORVERABR = "PASTCORVERABR";
    public static final String COLUMN_ALIMGANADO_PASTCORVERMAY = "PASTCORVERMAY";
    public static final String COLUMN_ALIMGANADO_PASTCORVERJUN = "PASTCORVERJUN";
    public static final String COLUMN_ALIMGANADO_PASTCORVERJUL = "PASTCORVERJUL";
    public static final String COLUMN_ALIMGANADO_PASTCORVERAGO = "PASTCORVERAGO";
    public static final String COLUMN_ALIMGANADO_PASTCORVERSEP = "PASTCORVERSEP";
    public static final String COLUMN_ALIMGANADO_PASTCORVEROCT = "PASTCORVEROCT";
    public static final String COLUMN_ALIMGANADO_PASTCORVERNOV = "PASTCORVERNOV";
    public static final String COLUMN_ALIMGANADO_PASTCORVERDIC = "PASTCORVERDIC";
    public static final String COLUMN_ALIMGANADO_PASTCORVERCOS = "PASTCORVERCOS";

    public static final String COLUMN_ALIMGANADO_PASTMAIZENE = "PASTMAIZENE";
    public static final String COLUMN_ALIMGANADO_PASTMAIZFEB = "PASTMAIZFEB";
    public static final String COLUMN_ALIMGANADO_PASTMAIZMAR = "PASTMAIZMAR";
    public static final String COLUMN_ALIMGANADO_PASTMAIZABR = "PASTMAIZABR";
    public static final String COLUMN_ALIMGANADO_PASTMAIZMAY = "PASTMAIZMAY";
    public static final String COLUMN_ALIMGANADO_PASTMAIZJUN = "PASTMAIZJUN";
    public static final String COLUMN_ALIMGANADO_PASTMAIZJUL = "PASTMAIZJUL";
    public static final String COLUMN_ALIMGANADO_PASTMAIZAGO = "PASTMAIZAGO";
    public static final String COLUMN_ALIMGANADO_PASTMAIZSEP = "PASTMAIZSEP";
    public static final String COLUMN_ALIMGANADO_PASTMAIZOCT = "PASTMAIZOCT";
    public static final String COLUMN_ALIMGANADO_PASTMAIZNOV = "PASTMAIZNOV";
    public static final String COLUMN_ALIMGANADO_PASTMAIZDIC = "PASTMAIZDIC";
    public static final String COLUMN_ALIMGANADO_PASTMAIZCOS = "PASTMAIZCOS";

    public static final String COLUMN_ALIMGANADO_PASTHENOSENE = "PASTHENOSENE";
    public static final String COLUMN_ALIMGANADO_PASTHENOSFEB = "PASTHENOSFEB";
    public static final String COLUMN_ALIMGANADO_PASTHENOSMAR = "PASTHENOSMAR";
    public static final String COLUMN_ALIMGANADO_PASTHENOSABR = "PASTHENOSABR";
    public static final String COLUMN_ALIMGANADO_PASTHENOSMAY = "PASTHENOSMAY";
    public static final String COLUMN_ALIMGANADO_PASTHENOSJUN = "PASTHENOSJUN";
    public static final String COLUMN_ALIMGANADO_PASTHENOSJUL = "PASTHENOSJUL";
    public static final String COLUMN_ALIMGANADO_PASTHENOSAGO = "PASTHENOSAGO";
    public static final String COLUMN_ALIMGANADO_PASTHENOSSEP = "PASTHENOSSEP";
    public static final String COLUMN_ALIMGANADO_PASTHENOSOCT = "PASTHENOSOCT";
    public static final String COLUMN_ALIMGANADO_PASTHENOSNOV = "PASTHENOSNOV";
    public static final String COLUMN_ALIMGANADO_PASTHENOSDIC = "PASTHENOSDIC";
    public static final String COLUMN_ALIMGANADO_PASTHENOSCOS = "PASTHENOSCOS";



    public static final String COLUMN_ALIMGANADO_PASTCONCOMENE = "PASTCONCOMENE";
    public static final String COLUMN_ALIMGANADO_PASTCONCOMFEB = "PASTCONCOMFEB";
    public static final String COLUMN_ALIMGANADO_PASTCONCOMMAR = "PASTCONCOMMAR";
    public static final String COLUMN_ALIMGANADO_PASTCONCOMABR = "PASTCONCOMABR";
    public static final String COLUMN_ALIMGANADO_PASTCONCOMMAY = "PASTCONCOMMAY";
    public static final String COLUMN_ALIMGANADO_PASTCONCOMJUN = "PASTCONCOMJUN";
    public static final String COLUMN_ALIMGANADO_PASTCONCOMJUL = "PASTCONCOMJUL";
    public static final String COLUMN_ALIMGANADO_PASTCONCOMAGO = "PASTCONCOMAGO";
    public static final String COLUMN_ALIMGANADO_PASTCONCOMSEP = "PASTCONCOMSEP";
    public static final String COLUMN_ALIMGANADO_PASTCONCOMOCT = "PASTCONCOMOCT";
    public static final String COLUMN_ALIMGANADO_PASTCONCOMNOV = "PASTCONCOMNOV";
    public static final String COLUMN_ALIMGANADO_PASTCONCOMDIC = "PASTCONCOMDIC";
    public static final String COLUMN_ALIMGANADO_PASTCONCOMCOS = "PASTCONCOMCOS";

    public static final String COLUMN_ALIMGANADO_PASTELPROPENE = "PASTELPROPENE";
    public static final String COLUMN_ALIMGANADO_PASTELPROPFEB = "PASTELPROPFEB";
    public static final String COLUMN_ALIMGANADO_PASTELPROPMAR = "PASTELPROPMAR";
    public static final String COLUMN_ALIMGANADO_PASTELPROPABR = "PASTELPROPABR";
    public static final String COLUMN_ALIMGANADO_PASTELPROPMAY = "PASTELPROPMAY";
    public static final String COLUMN_ALIMGANADO_PASTELPROPJUN = "PASTELPROPJUN";
    public static final String COLUMN_ALIMGANADO_PASTELPROPJUL = "PASTELPROPJUL";
    public static final String COLUMN_ALIMGANADO_PASTELPROPAGO = "PASTELPROPAGO";
    public static final String COLUMN_ALIMGANADO_PASTELPROPSEP = "PASTELPROPSEP";
    public static final String COLUMN_ALIMGANADO_PASTELPROPOCT = "PASTELPROPOCT";
    public static final String COLUMN_ALIMGANADO_PASTELPROPNOV = "PASTELPROPNOV";
    public static final String COLUMN_ALIMGANADO_PASTELPROPDIC = "PASTELPROPDIC";
    public static final String COLUMN_ALIMGANADO_PASTELPROPCOS = "PASTELPROPCOS";



    public static final String COLUMN_ALIMGANADO_PASTBLOQCOMENE = "PASTBLOQCOMENE";
    public static final String COLUMN_ALIMGANADO_PASTBLOQCOMFEB = "PASTBLOQCOMFEB";
    public static final String COLUMN_ALIMGANADO_PASTBLOQCOMMAR = "PASTBLOQCOMMAR";
    public static final String COLUMN_ALIMGANADO_PASTBLOQCOMABR = "PASTBLOQCOMABR";
    public static final String COLUMN_ALIMGANADO_PASTBLOQCOMMAY = "PASTBLOQCOMMAY";
    public static final String COLUMN_ALIMGANADO_PASTBLOQCOMJUN = "PASTBLOQCOMJUN";
    public static final String COLUMN_ALIMGANADO_PASTBLOQCOMJUL = "PASTBLOQCOMJUL";
    public static final String COLUMN_ALIMGANADO_PASTBLOQCOMAGO = "PASTBLOQCOMAGO";
    public static final String COLUMN_ALIMGANADO_PASTBLOQCOMSEP = "PASTBLOQCOMSEP";
    public static final String COLUMN_ALIMGANADO_PASTBLOQCOMOCT = "PASTBLOQCOMOCT";
    public static final String COLUMN_ALIMGANADO_PASTBLOQCOMNOV = "PASTBLOQCOMNOV";
    public static final String COLUMN_ALIMGANADO_PASTBLOQCOMDIC = "PASTBLOQCOMDIC";
    public static final String COLUMN_ALIMGANADO_PASTBLOQCOMCOS = "PASTBLOQCOMCOS";

    public static final String COLUMN_ALIMGANADO_PASTBLOQELPRENE = "PASTBLOQELPRENE";
    public static final String COLUMN_ALIMGANADO_PASTBLOQELPRFEB = "PASTBLOQELPRFEB";
    public static final String COLUMN_ALIMGANADO_PASTBLOQELPRMAR = "PASTBLOQELPRMAR";
    public static final String COLUMN_ALIMGANADO_PASTBLOQELPRABR = "PASTBLOQELPRABR";
    public static final String COLUMN_ALIMGANADO_PASTBLOQELPRMAY = "PASTBLOQELPRMAY";
    public static final String COLUMN_ALIMGANADO_PASTBLOQELPRJUN = "PASTBLOQELPRJUN";
    public static final String COLUMN_ALIMGANADO_PASTBLOQELPRJUL = "PASTBLOQELPRJUL";
    public static final String COLUMN_ALIMGANADO_PASTBLOQELPRAGO = "PASTBLOQELPRAGO";
    public static final String COLUMN_ALIMGANADO_PASTBLOQELPRSEP = "PASTBLOQELPRSEP";
    public static final String COLUMN_ALIMGANADO_PASTBLOQELPROCT = "PASTBLOQELPROCT";
    public static final String COLUMN_ALIMGANADO_PASTBLOQELPRNOV = "PASTBLOQELPRNOV";
    public static final String COLUMN_ALIMGANADO_PASBLOQELPRDIC = "PASBLOQELPRDIC";
    public static final String COLUMN_ALIMGANADO_PASTBLOQELPRCOS = "PASTBLOQELPRCOS";


    public static final String COLUMN_ALIMGANADO_PASTMELUREAENE = "PASTMELUREAENE";
    public static final String COLUMN_ALIMGANADO_PASTMELUREAFEB = "PASTMELUREAFEB";
    public static final String COLUMN_ALIMGANADO_PASTMELUREAMAR = "PASTMELUREAMAR";
    public static final String COLUMN_ALIMGANADO_PASTMELUREAABR = "PASTMELUREAABR";
    public static final String COLUMN_ALIMGANADO_PASTMELUREAMAY = "PASTMELUREAMAY";
    public static final String COLUMN_ALIMGANADO_PASTMELUREAJUN = "PASTMELUREAJUN";
    public static final String COLUMN_ALIMGANADO_PASTMELUREAJUL = "PASTMELUREAJUL";
    public static final String COLUMN_ALIMGANADO_PASTMELUREAAGO = "PASTMELUREAAGO";
    public static final String COLUMN_ALIMGANADO_PASTMELUREASEP = "PASTMELUREASEP";
    public static final String COLUMN_ALIMGANADO_PASTMELUREAOCT = "PASTMELUREAOCT";
    public static final String COLUMN_ALIMGANADO_PASTMELUREANOV = "PASTMELUREANOV";
    public static final String COLUMN_ALIMGANADO_PASMELUREADIC = "PASMELUREADIC";
    public static final String COLUMN_ALIMGANADO_PASTMELUREACOS = "PASTMELUREACOS";

    public static final String COLUMN_ALIMGANADO_PASTGRANOLEENE = "PASTGRANOLEENE";
    public static final String COLUMN_ALIMGANADO_PASTGRANOLEFEB = "PASTGRANOLEFEB";
    public static final String COLUMN_ALIMGANADO_PASTGRANOLEMAR = "PASTGRANOLEMAR";
    public static final String COLUMN_ALIMGANADO_PASTGRANOLEABR = "PASTGRANOLEABR";
    public static final String COLUMN_ALIMGANADO_PASTGRANOLEMAY = "PASTGRANOLEMAY";
    public static final String COLUMN_ALIMGANADO_PASTGRANOLEJUN = "PASTGRANOLEJUN";
    public static final String COLUMN_ALIMGANADO_PASTGRANOLEJUL = "PASTGRANOLEJUL";
    public static final String COLUMN_ALIMGANADO_PASTGRANOLEAGO = "PASTGRANOLEAGO";
    public static final String COLUMN_ALIMGANADO_PASTGRANOLESEP = "PASTGRANOLESEP";
    public static final String COLUMN_ALIMGANADO_PASTGRANOLEOCT = "PASTGRANOLEOCT";
    public static final String COLUMN_ALIMGANADO_PASTGRANOLENOV = "PASTGRANOLENOV";
    public static final String COLUMN_ALIMGANADO_PASGRANOLEDIC = "PASGRANOLEDIC";
    public static final String COLUMN_ALIMGANADO_PASTGRANOLECOS = "PASTGRANOLECOS";



    public static final String COLUMN_ALIMGANADO_PASTSALCOMENE = "PASTSALCOMENE";
    public static final String COLUMN_ALIMGANADO_PASTSALCOMFEB = "PASTSALCOMFEB";
    public static final String COLUMN_ALIMGANADO_PASTSALCOMMAR = "PASTSALCOMMAR";
    public static final String COLUMN_ALIMGANADO_PASTSALCOMABR = "PASTSALCOMABR";
    public static final String COLUMN_ALIMGANADO_PASTSALCOMMAY = "PASTSALCOMMAY";
    public static final String COLUMN_ALIMGANADO_PASTSALCOMJUN = "PASTSALCOMJUN";
    public static final String COLUMN_ALIMGANADO_PASTSALCOMJUL = "PASTSALCOMJUL";
    public static final String COLUMN_ALIMGANADO_PASTSALCOMAGO = "PASTSALCOMAGO";
    public static final String COLUMN_ALIMGANADO_PASTSALCOMSEP = "PASTSALCOMSEP";
    public static final String COLUMN_ALIMGANADO_PASTSALCOMOCT = "PASTSALCOMOCT";
    public static final String COLUMN_ALIMGANADO_PASTSALCOMNOV = "PASTSALCOMNOV";
    public static final String COLUMN_ALIMGANADO_PASSALCOMDIC = "PASSALCOMDIC";
    public static final String COLUMN_ALIMGANADO_PASTSALCOMCOS = "PASTSALCOMCOS";

    public static final String COLUMN_ALIMGANADO_PASTSALMINENE = "PASTSALMINENE";
    public static final String COLUMN_ALIMGANADO_PASTSALMINFEB = "PASTSALMINFEB";
    public static final String COLUMN_ALIMGANADO_PASTSALMINMAR = "PASTSALMINMAR";
    public static final String COLUMN_ALIMGANADO_PASTSALMINABR = "PASTSALMINABR";
    public static final String COLUMN_ALIMGANADO_PASTSALMINMAY = "PASTSALMINMAY";
    public static final String COLUMN_ALIMGANADO_PASTSALMINJUN = "PASTSALMINJUN";
    public static final String COLUMN_ALIMGANADO_PASTSALMINJUL = "PASTSALMINJUL";
    public static final String COLUMN_ALIMGANADO_PASTSALMINAGO = "PASTSALMINAGO";
    public static final String COLUMN_ALIMGANADO_PASTSALMINSEP = "PASTSALMINSEP";
    public static final String COLUMN_ALIMGANADO_PASTSALMINOCT = "PASTSALMINOCT";
    public static final String COLUMN_ALIMGANADO_PASTSALMINNOV = "PASTSALMINNOV";
    public static final String COLUMN_ALIMGANADO_PASSALMINDIC = "PASSALMINDIC";
    public static final String COLUMN_ALIMGANADO_PASTSALMINCOS = "PASTSALMINCOS";



    public static final String COLUMN_ALIMGANADO_PASTBLOQMINENE = "PASTBLOQMINENE";
    public static final String COLUMN_ALIMGANADO_PASTBLOQMINFEB = "PASTBLOQMINFEB";
    public static final String COLUMN_ALIMGANADO_PASTBLOQMINMAR = "PASTBLOQMINMAR";
    public static final String COLUMN_ALIMGANADO_PASTBLOQMINABR = "PASTBLOQMINABR";
    public static final String COLUMN_ALIMGANADO_PASTBLOQMINMAY = "PASTBLOQMINMAY";
    public static final String COLUMN_ALIMGANADO_PASTBLOQMINJUN = "PASTBLOQMINJUN";
    public static final String COLUMN_ALIMGANADO_PASTBLOQMINJUL = "PASTBLOQMINJUL";
    public static final String COLUMN_ALIMGANADO_PASTBLOQMINAGO = "PASTBLOQMINAGO";
    public static final String COLUMN_ALIMGANADO_PASTBLOQMINSEP = "PASTBLOQMINSEP";
    public static final String COLUMN_ALIMGANADO_PASTBLOQMINOCT = "PASTBLOQMINOCT";
    public static final String COLUMN_ALIMGANADO_PASTBLOQMINNOV = "PASTBLOQMINNOV";
    public static final String COLUMN_ALIMGANADO_PASBLOQMINDIC = "PASBLOQMINDIC";
    public static final String COLUMN_ALIMGANADO_PASTBLOQMINCOS = "PASTBLOQMINCOS";

    public static final String COLUMN_ALIMGANADO_PASTVITAMINENE = "PASTVITAMINENE";
    public static final String COLUMN_ALIMGANADO_PASTVITAMINFEB = "PASTVITAMINFEB";
    public static final String COLUMN_ALIMGANADO_PASTVITAMINMAR = "PASTVITAMINMAR";
    public static final String COLUMN_ALIMGANADO_PASTVITAMINABR = "PASTVITAMINABR";
    public static final String COLUMN_ALIMGANADO_PASTVITAMINMAY = "PASTVITAMINMAY";
    public static final String COLUMN_ALIMGANADO_PASTVITAMINJUN = "PASTVITAMINJUN";
    public static final String COLUMN_ALIMGANADO_PASTVITAMINJUL = "PASTVITAMINJUL";
    public static final String COLUMN_ALIMGANADO_PASTVITAMINAGO = "PASTVITAMINAGO";
    public static final String COLUMN_ALIMGANADO_PASTVITAMINSEP = "PASTVITAMINSEP";
    public static final String COLUMN_ALIMGANADO_PASTVITAMINOCT = "PASTVITAMINOCT";
    public static final String COLUMN_ALIMGANADO_PASTVITAMINNOV = "PASTVITAMINNOV";
    public static final String COLUMN_ALIMGANADO_PASVITAMINDIC = "PASVITAMINDIC";
    public static final String COLUMN_ALIMGANADO_PASTVITAMINCOS = "PASTVITAMINCOS";



    public static final String COLUMN_ALIMGANADO_PASTSELENIOENE = "PASTSELENIOENE";
    public static final String COLUMN_ALIMGANADO_PASTSELENIOFEB = "PASTSELENIOFEB";
    public static final String COLUMN_ALIMGANADO_PASTSELENIOMAR = "PASTSELENIOMAR";
    public static final String COLUMN_ALIMGANADO_PASTSELENIOABR = "PASTSELENIOABR";
    public static final String COLUMN_ALIMGANADO_PASTSELENIOMAY = "PASTSELENIOMAY";
    public static final String COLUMN_ALIMGANADO_PASTSELENIOJUN = "PASTSELENIOJUN";
    public static final String COLUMN_ALIMGANADO_PASTSELENIOJUL = "PASTSELENIOJUL";
    public static final String COLUMN_ALIMGANADO_PASTSELENIOAGO = "PASTSELENIOAGO";
    public static final String COLUMN_ALIMGANADO_PASTSELENIOSEP = "PASTSELENIOSEP";
    public static final String COLUMN_ALIMGANADO_PASTSELENIOOCT = "PASTSELENIOOCT";
    public static final String COLUMN_ALIMGANADO_PASTSELENIONOV = "PASTSELENIONOV";
    public static final String COLUMN_ALIMGANADO_PASSELENIODIC = "PASSELENIODIC";
    public static final String COLUMN_ALIMGANADO_PASTSELENIOCOS = "PASTSELENIOCOS";

    public static final String COLUMN_ALIMGANADO_PASTOTROTIPOENE = "PASTOTROTIPOENE";
    public static final String COLUMN_ALIMGANADO_PASTOTROTIPOFEB = "PASTOTROTIPOFEB";
    public static final String COLUMN_ALIMGANADO_PASTOTROTIPOMAR = "PASTOTROTIPOMAR";
    public static final String COLUMN_ALIMGANADO_PASTOTROTIPOABR = "PASTOTROTIPOABR";
    public static final String COLUMN_ALIMGANADO_PASTOTROTIPOMAY = "PASTOTROTIPOMAY";
    public static final String COLUMN_ALIMGANADO_PASTOTROTIPOJUN = "PASTOTROTIPOJUN";
    public static final String COLUMN_ALIMGANADO_PASTOTROTIPOJUL = "PASTOTROTIPOJUL";
    public static final String COLUMN_ALIMGANADO_PASTOTROTIPOAGO = "PASTOTROTIPOAGO";
    public static final String COLUMN_ALIMGANADO_PASTOTROTIPOSEP = "PASTOTROTIPOSEP";
    public static final String COLUMN_ALIMGANADO_PASTOTROTIPOOCT = "PASTOTROTIPOOCT";
    public static final String COLUMN_ALIMGANADO_PASTOTROTIPONOV = "PASTOTROTIPONOV";
    public static final String COLUMN_ALIMGANADO_PASOTROTIPODIC = "PASOTROTIPODIC";
    public static final String COLUMN_ALIMGANADO_PASTOTROTIPOCOS = "PASTOTROTIPOCOS";


    //Crear la tabla pecuario dieta
    public static final String CREAR_TABLA_PECUARIO_DIETAOVICAPRI = "CREATE TABLE " + TABLA_PECUARIO_DIETAOVICAPRI +
            "(" + COLUMN_ID_PECUDIETAOVICAPRI +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENC_PECUDIETAOVICAPRI +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTAGOSTENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTAGOSTFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTAGOSTMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTAGOSTABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTAGOSTMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTAGOSTJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTAGOSTJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTAGOSTAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTAGOSTSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTAGOSTOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTAGOSTNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTAGOSTDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTAGOSTCOS +

            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTPRADENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTPRADFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTPRADMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTPRADABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTPRADMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTPRADJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTPRADJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTPRADAGO+
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTPRADSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTPRADOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTPRADNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTPRADDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTPRADCOS +

            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTRASTROENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTRASTROFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTRASTROMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTRASTROABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTRASTROMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTRASTROJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTRASTROJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTRASTROAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTRASTROSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTRASTROOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTRASTRONOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTRASTRODIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTRASTROCOS +


            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCORVERENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCORVERFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCORVERMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCORVERABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCORVERMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCORVERJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCORVERJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCORVERAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCORVERSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCORVEROCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCORVERNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCORVERDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCORVERCOS +


            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMAIZENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMAIZFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMAIZMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMAIZABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMAIZMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMAIZJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMAIZJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMAIZAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMAIZSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMAIZOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMAIZNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMAIZDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMAIZCOS +


            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTHENOSENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTHENOSFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTHENOSMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTHENOSABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTHENOSMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTHENOSJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTHENOSJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTHENOSAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTHENOSSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTHENOSOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTHENOSNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTHENOSDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTHENOSCOS +



            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCONCOMENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCONCOMFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCONCOMMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCONCOMABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCONCOMMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCONCOMJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCONCOMJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCONCOMAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCONCOMSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCONCOMOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCONCOMNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCONCOMDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTCONCOMCOS +


            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTELPROPENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTELPROPFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTELPROPMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTELPROPABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTELPROPMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTELPROPJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTELPROPJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTELPROPAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTELPROPSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTELPROPOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTELPROPNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTELPROPDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTELPROPCOS +




            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQCOMENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQCOMFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQCOMMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQCOMABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQCOMMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQCOMJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQCOMJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQCOMAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQCOMSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQCOMOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQCOMNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQCOMDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQCOMCOS+


            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQELPRENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQELPRFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQELPRMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQELPRABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQELPRMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQELPRJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQELPRJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQELPRAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQELPRSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQELPROCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQELPRNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASBLOQELPRDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQELPRCOS +



            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMELUREAENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMELUREAFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMELUREAMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMELUREAABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMELUREAMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMELUREAJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMELUREAJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMELUREAAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMELUREASEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMELUREAOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMELUREANOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASMELUREADIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTMELUREACOS+


            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTGRANOLEENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTGRANOLEFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTGRANOLEMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTGRANOLEABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTGRANOLEMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTGRANOLEJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTGRANOLEJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTGRANOLEAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTGRANOLESEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTGRANOLEOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTGRANOLENOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASGRANOLEDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTGRANOLECOS +


            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALCOMENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALCOMFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALCOMMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALCOMABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALCOMMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALCOMJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALCOMJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALCOMAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALCOMSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALCOMOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALCOMNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASSALCOMDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALCOMCOS+


            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALMINENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALMINFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALMINMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALMINABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALMINMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALMINJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALMINJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALMINAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALMINSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALMINOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALMINNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASSALMINDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSALMINCOS +



            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQMINENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQMINFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQMINMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQMINABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQMINMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQMINJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQMINJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQMINAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQMINSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQMINOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQMINNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASBLOQMINDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTBLOQMINCOS+


            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTVITAMINENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTVITAMINFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTVITAMINMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTVITAMINABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTVITAMINMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTVITAMINJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTVITAMINJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTVITAMINAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTVITAMINSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTVITAMINOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTVITAMINNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASVITAMINDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTVITAMINCOS +





            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSELENIOENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSELENIOFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSELENIOMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSELENIOABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSELENIOMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSELENIOJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSELENIOJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSELENIOAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSELENIOSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSELENIOOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSELENIONOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASSELENIODIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTSELENIOCOS+


            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTOTROTIPOENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTOTROTIPOFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTOTROTIPOMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTOTROTIPOABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTOTROTIPOMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTOTROTIPOJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTOTROTIPOJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTOTROTIPOAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTOTROTIPOSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTOTROTIPOOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTOTROTIPONOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASOTROTIPODIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PASTOTROTIPOCOS +
            " VARCHAR); ";







    //Tabla Pecuario eventos de unidad de produccion
    public static final String TABLA_PECUARIO_EVEUNPRO = "TBEVEUNPRO";

    public static final String COLUMN_ID_PECUEVEUNPRO = "IDEVEUNPRO";
    public static final String COLUMN_FOLIOENC_PECUEVEUNPRO = "FOEVEUNPRO";

    public static final String COLUMN_ALIMGANADO_EVEESCAFORENE = "EVEESCAFORENE";
    public static final String COLUMN_ALIMGANADO_EVEESCAFORFEB = "EVEESCAFORFEB";
    public static final String COLUMN_ALIMGANADO_EVEESCAFORMAR = "EVEESCAFORMAR";
    public static final String COLUMN_ALIMGANADO_EVEESCAFORABR = "EVEESCAFORABR";
    public static final String COLUMN_ALIMGANADO_EVEESCAFORMAY = "EVEESCAFORMAY";
    public static final String COLUMN_ALIMGANADO_EVEESCAFORJUN = "EVEESCAFORJUN";
    public static final String COLUMN_ALIMGANADO_EVEESCAFORJUL = "EVEESCAFORJUL";
    public static final String COLUMN_ALIMGANADO_EVEESCAFORAGO = "EVEESCAFORAGO";
    public static final String COLUMN_ALIMGANADO_EVEESCAFORSEP = "EVEESCAFORSEP";
    public static final String COLUMN_ALIMGANADO_EVEESCAFOROCT = "EVEESCAFOROCT";
    public static final String COLUMN_ALIMGANADO_EVEESCAFORNOV = "EVEESCAFORNOV";
    public static final String COLUMN_ALIMGANADO_EVEESCAFORDIC = "EVEESCAFORDIC";



    public static final String COLUMN_ALIMGANADO_EVECOMPFORENE = "EVECOMPFORENE";
    public static final String COLUMN_ALIMGANADO_EVECOMPFORFEB = "EVECOMPFORFEB";
    public static final String COLUMN_ALIMGANADO_EVECOMPFORMAR = "EVECOMPFORMAR";
    public static final String COLUMN_ALIMGANADO_EVECOMPFORABR = "EVECOMPFORABR";
    public static final String COLUMN_ALIMGANADO_EVECOMPFORMAY = "EVECOMPFORMAY";
    public static final String COLUMN_ALIMGANADO_EVECOMPFORJUN = "EVECOMPFORJUN";
    public static final String COLUMN_ALIMGANADO_EVECOMPFORJUL = "EVECOMPFORJUL";
    public static final String COLUMN_ALIMGANADO_EVECOMPFORAGO = "EVECOMPFORAGO";
    public static final String COLUMN_ALIMGANADO_EVECOMPFORSEP = "EVECOMPFORSEP";
    public static final String COLUMN_ALIMGANADO_EVECOMPFOROCT = "EVECOMPFOROCT";
    public static final String COLUMN_ALIMGANADO_EVECOMPFORNOV = "EVECOMPFORNOV ";
    public static final String COLUMN_ALIMGANADO_EVECOMPFORDIC = "EVECOMPFORDIC";
    public static final String COLUMN_ALIMGANADO_EVECOMPFORCOST = "EVECOMPFORCOST";


    public static final String COLUMN_ALIMGANADO_EVEMANTPRADENE = "EVEMANTPRADENE";
    public static final String COLUMN_ALIMGANADO_EVEMANTPRADFEB = "EVEMANTPRADFEB";
    public static final String COLUMN_ALIMGANADO_EVEMANTPRADMAR = "EVEMANTPRADMAR";
    public static final String COLUMN_ALIMGANADO_EVEMANTPRADABR = "EVEMANTPRADABR";
    public static final String COLUMN_ALIMGANADO_EVEMANTPRADMAY = "EVEMANTPRADMAY";
    public static final String COLUMN_ALIMGANADO_EVEMANTPRADJUN = "EVEMANTPRADJUN";
    public static final String COLUMN_ALIMGANADO_EVEMANTPRADJUL = "EVEMANTPRADJUL";
    public static final String COLUMN_ALIMGANADO_EVEMANTPRADAGO = "EVEMANTPRADAGO";
    public static final String COLUMN_ALIMGANADO_EVEMANTPRADSEP = "EVEMANTPRADSEP";
    public static final String COLUMN_ALIMGANADO_EVEMANTPRADOCT = "EVEMANTPRADOCT";
    public static final String COLUMN_ALIMGANADO_EVEMANTPRADNOV = "EVEMANTPRADNOV ";
    public static final String COLUMN_ALIMGANADO_EVEMANTPRADDIC = "EVEMANTPRADDIC";
    public static final String COLUMN_ALIMGANADO_EVEMANTPRADCOST = "EVEMANTPRADCOST";


    public static final String COLUMN_ALIMGANADO_EVEALIMAGOSENE = "EVEALIMAGOSENE";
    public static final String COLUMN_ALIMGANADO_EVEALIMAGOSFEB = "EVEALIMAGOSFEB";
    public static final String COLUMN_ALIMGANADO_EVEALIMAGOSMAR = "EVEALIMAGOSMAR";
    public static final String COLUMN_ALIMGANADO_EVEALIMAGOSABR = "EVEALIMAGOSABR";
    public static final String COLUMN_ALIMGANADO_EVEALIMAGOSMAY = "EVEALIMAGOSMAY";
    public static final String COLUMN_ALIMGANADO_EVEALIMAGOSJUN = "EVEALIMAGOSJUN";
    public static final String COLUMN_ALIMGANADO_EVEALIMAGOSJUL = "EVEALIMAGOSJUL";
    public static final String COLUMN_ALIMGANADO_EVEALIMAGOSAGO = "EVEALIMAGOSAGO";
    public static final String COLUMN_ALIMGANADO_EVEALIMAGOSSEP = "EVEALIMAGOSSEP";
    public static final String COLUMN_ALIMGANADO_EVEALIMAGOSOCT = "EVEALIMAGOSOCT";
    public static final String COLUMN_ALIMGANADO_EVEALIMAGOSNOV = "EVEALIMAGOSNOV ";
    public static final String COLUMN_ALIMGANADO_EVEALIMAGOSDIC = "EVEALIMAGOSDIC";
    public static final String COLUMN_ALIMGANADO_EVEALIMAGOSCOST = "EVEALIMAGOSCOST";

    //Crear la tabla pecuario eventos de unidad de produccion
    public static final String CREAR_TABLA_PECUARIO_EVEUNPRO = "CREATE TABLE " + TABLA_PECUARIO_EVEUNPRO +
            "(" + COLUMN_ID_PECUEVEUNPRO +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENC_PECUEVEUNPRO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEESCAFORENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEESCAFORFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEESCAFORMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEESCAFORABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEESCAFORMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEESCAFORJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEESCAFORJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEESCAFORAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEESCAFORSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEESCAFOROCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEESCAFORNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEESCAFORDIC +


            " VARCHAR, "+ COLUMN_ALIMGANADO_EVECOMPFORENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVECOMPFORFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVECOMPFORMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVECOMPFORABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVECOMPFORMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVECOMPFORJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVECOMPFORJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVECOMPFORAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVECOMPFORSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVECOMPFOROCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVECOMPFORNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVECOMPFORDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVECOMPFORCOST +


            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEMANTPRADENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEMANTPRADFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEMANTPRADMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEMANTPRADABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEMANTPRADMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEMANTPRADJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEMANTPRADJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEMANTPRADAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEMANTPRADSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEMANTPRADOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEMANTPRADNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEMANTPRADDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEMANTPRADCOST +


            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEALIMAGOSENE +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEALIMAGOSFEB +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEALIMAGOSMAR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEALIMAGOSABR +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEALIMAGOSMAY +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEALIMAGOSJUN +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEALIMAGOSJUL +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEALIMAGOSAGO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEALIMAGOSSEP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEALIMAGOSOCT +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEALIMAGOSNOV +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEALIMAGOSDIC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_EVEALIMAGOSCOST +
            " VARCHAR); ";




    //Tabla Pecuario agregar alimentos pecuario
    public static final String TABLA_PECUARIO_AGREALPEC = "TBAGREALPEC";

    public static final String COLUMN_ID_PECUAGREALPEC = "IDAGREALPEC";
    public static final String COLUMN_FOLIOENC_PECAGREALPEC = "FOAGREALPEC";

    public static final String COLUMN_ALIMGANADO_PECUALIMENTOCOM = "PECUALIMENTOCOM";
    public static final String COLUMN_ALIMGANADO_PECUALIMENTOCOTRO = "PECUALIMENTOCOTRO";
    public static final String COLUMN_ALIMGANADO_PECUALIMLUGCOMP = "PECUALIMLUGCOMP";
    public static final String COLUMN_ALIMGANADO_PECUALIMPRECCOMP = "PECUALIMPRECCOMP";


    //Crear la tabla pecuario eventos de unidad de produccion
    public static final String CREAR_TABLA_PECUARIO_AGREALPEC = "CREATE TABLE " + TABLA_PECUARIO_AGREALPEC +
            "(" + COLUMN_ID_PECUAGREALPEC +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENC_PECAGREALPEC +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PECUALIMENTOCOM +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PECUALIMENTOCOTRO +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PECUALIMLUGCOMP +
            " VARCHAR, "+ COLUMN_ALIMGANADO_PECUALIMPRECCOMP +
            " VARCHAR); ";


    //Tabla Pecuario manejo de agostadero
    public static final String TABLA_PECUARIO_MANEAGOSTAD = "TBMANEAGOSTAD";

    public static final String COLUMN_ID_PECUMANAGOST = "IDMANAGOST";
    public static final String COLUMN_FOLIOENC_PECUMANAGOST = "FOMANAGOST";

    public static final String COLUMN_MANAGOSTADERO_PECUDIVPOTRERO = "PECUDIVPOTRERO";
    public static final String COLUMN_MANAGOSTADERO_PECUCERCOELECT = "PECUCERCOELECT";
    public static final String COLUMN_MANAGOSTADERO_PECUAJUSTCARGA = "PECUAJUSTCARGA";
    public static final String COLUMN_MANAGOSTADERO_PECUPASTROTACI = "PECUPASTROTACI";
    public static final String COLUMN_MANAGOSTADERO_PECUMANEJOEXTE = "PECUMANEJOEXTE";
    public static final String COLUMN_MANAGOSTADERO_PECUCONTABREVAD = "PECUCONTABREVAD";
    public static final String COLUMN_MANAGOSTADERO_PECUCANTIDABREV = "PECUCANTIDABREV";


    public static final String COLUMN_MANAGOSTADERO_PECUPRODFORREJ = "PECUPRODFORREJ";
    public static final String COLUMN_MANAGOSTADERO_PECUPRODCONCOM = "PECUPRODCONCOM";
    public static final String COLUMN_MANAGOSTADERO_PECUPRODENSILA = "PECUPRODENSILA";
    public static final String COLUMN_MANAGOSTADERO_PECUPRODHENOS = "PECUPRODHENOS";
    public static final String COLUMN_MANAGOSTADERO_PECUPRODMINERAL = "PECUPRODMINERAL";
    public static final String COLUMN_MANAGOSTADERO_PECUPRODGRANOS = "PECUPRODGRANOS";
    public static final String COLUMN_MANAGOSTADERO_PECUPRODUCOTROS = "PECUPRODUCOTROS";
    public static final String COLUMN_MANAGOSTADERO_PECUPRODUEDTOTR = "PECUPRODUEDTOTR";
    public static final String COLUMN_MANAGOSTADERO_PECUPRODUCNINGUN = "PECUPRODUCNINGUN";


    public static final String COLUMN_MANAGOSTADERO_PECUSEQPROLONG = "PECUSEQPROLONG";
    public static final String COLUMN_MANAGOSTADERO_PECUPOCADISPON = "PECUPOCADISPON";
    public static final String COLUMN_MANAGOSTADERO_PECUMUYCAROSADQ = "PECUMUYCAROSADQ";
    public static final String COLUMN_MANAGOSTADERO_PECUPOCOTERRENO = "PECUPOCOTERRENO";
    public static final String COLUMN_MANAGOSTADERO_PECUNOCONTRECUR = "PECUNOCONTRECUR";
    public static final String COLUMN_MANAGOSTADERO_PECUNOTENERCAPAC = "PECUNOTENERCAPAC";
    public static final String COLUMN_MANAGOSTADERO_PECUINSUFICMANOB = "PECUINSUFICMANOB";
    public static final String COLUMN_MANAGOSTADERO_PECUTIERRAPOCVAL = "PECUTIERRAPOCVAL";
    public static final String COLUMN_MANAGOSTADERO_PECUOTROPROBLEMF = "PECUOTROPROBLEMF";
    public static final String COLUMN_MANAGOSTADERO_PECUEDTOTPROBLEMF = "PECUEDTOTPROBLEMF";




    public static final String COLUMN_MANAGOSTADERO_PECUSUPLCOSTOCONC = "PECUSUPLCOSTOCONC";
    public static final String COLUMN_MANAGOSTADERO_PECUSUPLPOCDISPON = "PECUSUPLPOCDISPON";
    public static final String COLUMN_MANAGOSTADERO_PECUSUPLDIETNOBAL = "PECUSUPLDIETNOBAL";
    public static final String COLUMN_MANAGOSTADERO_PECUSUPLNOTENCONOC = "PECUSUPLNOTENCONOC";
    public static final String COLUMN_MANAGOSTADERO_PECUSUPLMUSCBLANCO = "PECUSUPLMUSCBLANCO";
    public static final String COLUMN_MANAGOSTADERO_PECUSUPLEMOTRO = "PECUSUPLEMOTRO";
    public static final String COLUMN_MANAGOSTADERO_PECUEDTSUPLOTROESP = "PECUEDTSUPLOTROESP";

    //Crear la tabla manejo de agostadero
    public static final String CREAR_TABLA_PECUARIO_MANEAGOSTAD = "CREATE TABLE " + TABLA_PECUARIO_MANEAGOSTAD +
            "(" + COLUMN_ID_PECUMANAGOST +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENC_PECUMANAGOST +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUDIVPOTRERO +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUCERCOELECT +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUAJUSTCARGA +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUPASTROTACI +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUMANEJOEXTE +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUCONTABREVAD +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUCANTIDABREV +


            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUPRODFORREJ +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUPRODCONCOM +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUPRODENSILA +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUPRODHENOS +

            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUPRODMINERAL +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUPRODGRANOS +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUPRODUCOTROS +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUPRODUEDTOTR +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUPRODUCNINGUN +


            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUSEQPROLONG +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUPOCADISPON +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUMUYCAROSADQ +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUPOCOTERRENO +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUNOCONTRECUR +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUNOTENERCAPAC +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUINSUFICMANOB +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUTIERRAPOCVAL +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUOTROPROBLEMF +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUEDTOTPROBLEMF +


            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUSUPLCOSTOCONC +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUSUPLPOCDISPON +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUSUPLDIETNOBAL +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUSUPLNOTENCONOC +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUSUPLMUSCBLANCO +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUSUPLEMOTRO +
            " VARCHAR, "+ COLUMN_MANAGOSTADERO_PECUEDTSUPLOTROESP +
            " VARCHAR); ";








    //Tabla Reproduccion , genetica y parametros reproductivos
    public static final String TABLA_PECUARIO_REPRODGENETICA = "TBPECREPRODGEN";

    public static final String COLUMN_ID_PECUREPRODGEN = "IDREPRODGEN";
    public static final String COLUMN_FOLIOENC_PECUREPRODGEN = "FOREPRODGEN";

    public static final String COLUMN_REPRODGENETICA_REPRODMONTLIBRE = "REPRODMONTLIBRE";
    public static final String COLUMN_REPRODGENETICA_REPRODMONTCONTRL = "REPRODMONTCONTRL";
    public static final String COLUMN_REPRODGENETICA_REPRODMONTAINSEM = "REPRODMONTAINSEM";
    public static final String COLUMN_REPRODGENETICA_REPRODMONTAINSART = "REPRODMONTAINSART";
    public static final String COLUMN_REPRODGENETICA_REPRODSINCRHEMBR = "REPRODSINCRHEMBR";
    public static final String COLUMN_REPRODGENETICA_REPRODDIAGNGESTAC = "REPRODDIAGNGESTAC";
    public static final String COLUMN_REPRODGENETICA_REPRODFERTSEMENT = "REPRODFERTSEMENT";
    public static final String COLUMN_REPRODGENETICA_REPRODINSEMINPROD = "REPRODINSEMINPROD";
    public static final String COLUMN_REPRODGENETICA_REPRODOTROESPECIF = "REPRODOTROESPECIF";
    public static final String COLUMN_REPRODGENETICA_REPRODEDTOTROESPEC = "REPRODEDTOTROESPEC";

    public static final String COLUMN_REPRODGENETICA_REPRPROBPOCPART = "REPRPROBPOCPART";
    public static final String COLUMN_REPRODGENETICA_REPRPROBHEMBTCAR = "REPRPROBHEMBTCAR";
    public static final String COLUMN_REPRODGENETICA_REPRPROBABORTOS = "REPRPROBABORTOS";
    public static final String COLUMN_REPRODGENETICA_REPRPROBCOSTOTEC = "REPRPROBCOSTOTEC";
    public static final String COLUMN_REPRODGENETICA_REPRPROBCAPACINO = "REPRPROBCAPACINO";
    public static final String COLUMN_REPRODGENETICA_REPRPROBPOCADISP = "REPRPROBPOCADISP";
    public static final String COLUMN_REPRODGENETICA_REPRPROBOTROESPC = "REPRPROBOTROESPC";
    public static final String COLUMN_REPRODGENETICA_REPRPROBOTROEDTESP = "REPRPROBOTROEDTESP";

    public static final String COLUMN_REPRODGENETICA_REPRGENEVALSEM = "REPRGENEVALSEM";
    public static final String COLUMN_REPRODGENETICA_REPRGENADAPGAN = "REPRGENADAPGAN";
    public static final String COLUMN_REPRODGENETICA_REPRGENCAPCRUZ = "REPRGENCAPCRUZ";
    public static final String COLUMN_REPRODGENETICA_REPRGENDISPSEM = "REPRGENDISPSEM";
    public static final String COLUMN_REPRODGENETICA_REPRGENOTROPRO = "REPRGENOTROPRO";
    public static final String COLUMN_REPRODGENETICA_REPRGENEDTOTRO = "REPRGENEDTOTRO";

    public static final String COLUMN_REPRODGENETICA_PARAMHEMBPARIDO = "PARAMHEMBPARIDO";
    public static final String COLUMN_REPRODGENETICA_PARAMTIEMPOPART = "PARAMTIEMPOPART";
    public static final String COLUMN_REPRODGENETICA_PARAMEDADPPARTO = "PARAMEDADPPARTO";
    public static final String COLUMN_REPRODGENETICA_PARAMEDADDHEMBR = "PARAMEDADDHEMBR";
    public static final String COLUMN_REPRODGENETICA_PARAMNUMCRPPART = "PARAMNUMCRPPART";
    public static final String COLUMN_REPRODGENETICA_PARAMNUMPALANIO = "PARAMNUMPALANIO";
    public static final String COLUMN_REPRODGENETICA_PARAMPESONACERC = "PARAMPESONACERC";
    public static final String COLUMN_REPRODGENETICA_PARAMPESODESTET = "PARAMPESODESTET";
    public static final String COLUMN_REPRODGENETICA_PARAMEDADDESTET = "PARAMEDADDESTET";
    public static final String COLUMN_REPRODGENETICA_PARAMMORTDESTET = "PARAMMORTDESTET";
    public static final String COLUMN_REPRODGENETICA_PARAMPESOVENTAA = "PARAMPESOVENTAA";
    public static final String COLUMN_REPRODGENETICA_PARAMEDADVENTAA = "PARAMEDADVENTAA";
    public static final String COLUMN_REPRODGENETICA_PARAMNUMVIENTRE = "PARAMNUMVIENTRE";
    public static final String COLUMN_REPRODGENETICA_PARAMVOLLECHEDI = "PARAMVOLLECHEDI";
    public static final String COLUMN_REPRODGENETICA_PARAMNUMDORDENI = "PARAMNUMDORDENI";
    public static final String COLUMN_REPRODGENETICA_PARAMVOLPLECHEV = "PARAMVOLPLECHEV";
    public static final String COLUMN_REPRODGENETICA_PARAMNUMCRIASAN = "PARAMNUMCRIASAN";
    public static final String COLUMN_REPRODGENETICA_PARAMNUMHEMRANI = "PARAMNUMHEMRANI";

    //Crear la tabla reproduccion genetica
    public static final String CREAR_TABLA_PECUARIO_REPRODGENETICA = "CREATE TABLE " + TABLA_PECUARIO_REPRODGENETICA +
            "(" + COLUMN_ID_PECUREPRODGEN +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENC_PECUREPRODGEN +

            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRODMONTLIBRE +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRODMONTCONTRL +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRODMONTAINSEM +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRODMONTAINSART +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRODSINCRHEMBR +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRODDIAGNGESTAC +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRODFERTSEMENT +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRODINSEMINPROD +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRODOTROESPECIF +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRODEDTOTROESPEC +


            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRPROBPOCPART +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRPROBHEMBTCAR +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRPROBABORTOS +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRPROBCOSTOTEC +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRPROBCAPACINO +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRPROBPOCADISP +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRPROBOTROESPC +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRPROBOTROEDTESP +


            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRGENEVALSEM +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRGENADAPGAN +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRGENCAPCRUZ +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRGENDISPSEM +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRGENOTROPRO +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_REPRGENEDTOTRO +


            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMHEMBPARIDO +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMTIEMPOPART +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMEDADPPARTO +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMEDADDHEMBR +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMNUMCRPPART +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMNUMPALANIO +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMPESONACERC +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMPESODESTET +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMEDADDESTET +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMMORTDESTET +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMPESOVENTAA +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMEDADVENTAA +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMNUMVIENTRE +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMVOLLECHEDI +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMNUMDORDENI +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMVOLPLECHEV +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMNUMCRIASAN +
            " VARCHAR, "+ COLUMN_REPRODGENETICA_PARAMNUMHEMRANI +
            " VARCHAR); ";





    //Tabla manejo sanitario ganado
    public static final String TABLA_PECUARIO_MANEJSANGAN = "TBMANEJSANGAN";

    public static final String COLUMN_ID_PECUMANEJSANGAN = "IDMANEJSANGAN";
    public static final String COLUMN_FOLIOENC_PECUMANEJSANGAN = "FOMANEJSANGAN";

    public static final String COLUMN_MANEJSANGAN_MANEJOSANCAMZOO = "MANEJOSANCAMZOO";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANTUBERC = "MANEJOSANTUBERC";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANRABIAP = "MANEJOSANRABIAP";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANGARRAP = "MANEJOSANGARRAP";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANBRUCEL = "MANEJOSANBRUCEL";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANOTROCA = "MANEJOSANOTROCA";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANEDTOTR = "MANEJOSANEDTOTR";

    public static final String COLUMN_MANEJSANGAN_MANEJOSANPROVAC = "MANEJOSANPROVAC";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANNEUMON = "MANEJOSANNEUMON";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANDOBLEV = "MANEJOSANDOBLEV";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANTRIPLE = "MANEJOSANTRIPLE";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANCLOSTR = "MANEJOSANCLOSTR";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANDERRIE = "MANEJOSANDERRIE";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANLEPTOS = "MANEJOSANLEPTOS";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANOTRAVA = "MANEJOSANOTRAVA";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANEDTOTV = "MANEJOSANEDTOTV";

    public static final String COLUMN_MANEJSANGAN_MANEJOSANCGARRA = "MANEJOSANCGARRA";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANCONGAR = "MANEJOSANCONGAR";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANGAREOT = "MANEJOSANGAREOT";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANGARCOS = "MANEJOSANGARCOS";

    public static final String COLUMN_MANEJSANGAN_MANEJOSANANAPAR = "MANEJOSANANAPAR";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANFREDES = "MANEJOSANFREDES";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANFREOTR = "MANEJOSANFREOTR";

    public static final String COLUMN_MANEJSANGAN_MANEJOSANPERPAR = "MANEJOSANPERPAR";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANABORTO = "MANEJOSANABORTO";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANDIARRE = "MANEJOSANDIARRE";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANSEPTIC = "MANEJOSANSEPTIC";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANENFRES = "MANEJOSANENFRES";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANMASTIT = "MANEJOSANMASTIT";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANRABIAD = "MANEJOSANRABIAD";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANOCULAR = "MANEJOSANOCULAR";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANGABARR = "MANEJOSANGABARR";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANECTIMA = "MANEJOSANECTIMA";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANPARASA = "MANEJOSANPARASA";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANOTROPR = "MANEJOSANOTROPR";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANPREDTO = "MANEJOSANPREDTO";

    public static final String COLUMN_MANEJSANGAN_MANEJOSANBAJFER = "MANEJOSANBAJFER";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANEDADDE = "MANEJOSANEDADDE";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANBAJPRO = "MANEJOSANBAJPRO";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANENFERM = "MANEJOSANENFERM";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANTEMPER = "MANEJOSANTEMPER";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANPROPAT = "MANEJOSANPROPAT";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANOTRODE = "MANEJOSANOTRODE";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANEDTODE = "MANEJOSANEDTODE";


    public static final String COLUMN_MANEJSANGAN_MANEJOSANCOSTME = "MANEJOSANCOSTME";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANCAPCEN = "MANEJOSANCAPCEN";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANREGINF = "MANEJOSANREGINF";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANDISVET = "MANEJOSANDISVET";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANCOSVET = "MANEJOSANCOSVET";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANDIAGSI = "MANEJOSANDIAGSI";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANOTROSA = "MANEJOSANOTROSA";
    public static final String COLUMN_MANEJSANGAN_MANEJOSANEDTOSA = "MANEJOSANEDTOSA";

    //Crear la tabla manejo SANITARIO
    public static final String CREAR_TABLA_PECUARIO_MANEJSANGAN = "CREATE TABLE " + TABLA_PECUARIO_MANEJSANGAN +
            "(" + COLUMN_ID_PECUMANEJSANGAN +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENC_PECUMANEJSANGAN +

            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANCAMZOO +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANTUBERC +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANRABIAP +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANGARRAP +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANBRUCEL +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANOTROCA +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANEDTOTR +

            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANPROVAC +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANNEUMON +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANDOBLEV +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANTRIPLE +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANCLOSTR +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANDERRIE +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANLEPTOS +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANOTRAVA +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANEDTOTV +


            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANCGARRA +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANCONGAR +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANGAREOT +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANGARCOS +

            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANANAPAR +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANFREDES +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANFREOTR +


            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANPERPAR +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANABORTO +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANDIARRE +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANSEPTIC +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANENFRES +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANMASTIT +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANRABIAD +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANOCULAR +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANGABARR +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANECTIMA +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANPARASA +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANOTROPR +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANPREDTO +


            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANBAJFER +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANEDADDE +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANBAJPRO +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANENFERM +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANTEMPER +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANPROPAT +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANOTRODE +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANEDTODE +


            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANCOSTME +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANCAPCEN +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANREGINF +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANDISVET +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANCOSVET +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANDIAGSI +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANOTROSA +
            " VARCHAR, "+ COLUMN_MANEJSANGAN_MANEJOSANEDTOSA +
            " VARCHAR); ";



    //Tabla Pecuario manejo sanitario ordeña
    public static final String TABLA_PECUARIO_MANSANOR = "TBMANSANOR";

    public static final String COLUMN_ID_PECUMANSANOR = "IDMANSANOR";
    public static final String COLUMN_FOLIOENC_PECMANSANOR = "FOMANSANOR";

    public static final String COLUMN_MANSANOR_MANEJOSANDIAMAS = "MANEJOSANDIAMAS";
    public static final String COLUMN_MANSANOR_MANEJOSANEDTMAS = "MANEJOSANEDTMAS";
    public static final String COLUMN_MANSANOR_MANEJOSANCOSTPR = "MANEJOSANCOSTPR";

    public static final String COLUMN_MANSANOR_MANEJOSANLAVUBR = "MANEJOSANLAVUBR";
    public static final String COLUMN_MANSANOR_MANEJOSANSECDES = "MANEJOSANSECDES";
    public static final String COLUMN_MANSANOR_MANEJOSANDESPUN = "MANEJOSANDESPUN";
    public static final String COLUMN_MANSANOR_MANEJOSANUSOSEL = "MANEJOSANUSOSEL";
    public static final String COLUMN_MANSANOR_MANEJOSANAPLANT = "MANEJOSANAPLANT";
    public static final String COLUMN_MANSANOR_MANEJOSANOTRORD = "MANEJOSANOTRORD";
    public static final String COLUMN_MANSANOR_MANEJOSANEDTOOR = "MANEJOSANEDTOOR";
    public static final String COLUMN_MANSANOR_MANEJOSANNINORD = "MANEJOSANNINORD";
    public static final String COLUMN_MANSANOR_MANEJOSANCOSTOR = "MANEJOSANCOSTOR";


    //Crear la tabla pecuario eventos de unidad de produccion
    public static final String CREAR_TABLA_PECUARIO_MANSANOR = "CREATE TABLE " + TABLA_PECUARIO_MANSANOR +
            "(" + COLUMN_ID_PECUMANSANOR +
            " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_FOLIOENC_PECMANSANOR +

            " VARCHAR, "+ COLUMN_MANSANOR_MANEJOSANDIAMAS +
            " VARCHAR, "+ COLUMN_MANSANOR_MANEJOSANEDTMAS +
            " VARCHAR, "+ COLUMN_MANSANOR_MANEJOSANCOSTPR +

            " VARCHAR, "+ COLUMN_MANSANOR_MANEJOSANLAVUBR +
            " VARCHAR, "+ COLUMN_MANSANOR_MANEJOSANSECDES +
            " VARCHAR, "+ COLUMN_MANSANOR_MANEJOSANDESPUN +
            " VARCHAR, "+ COLUMN_MANSANOR_MANEJOSANUSOSEL +
            " VARCHAR, "+ COLUMN_MANSANOR_MANEJOSANAPLANT +
            " VARCHAR, "+ COLUMN_MANSANOR_MANEJOSANOTRORD +
            " VARCHAR, "+ COLUMN_MANSANOR_MANEJOSANEDTOOR +
            " VARCHAR, "+ COLUMN_MANSANOR_MANEJOSANNINORD +
            " VARCHAR, "+ COLUMN_MANSANOR_MANEJOSANCOSTOR +
            " VARCHAR); ";

}









