package com.example.geosegalmex.PAROperativo;

public class PAR_operativo_bd {


    public static final String TABLA_BD = "TB_PAR_OPERATIVO";
    public static final String COLUMN_FOLIO= "FOLIO";
    public static final String COLUMN_FECHA= "FECHA";
    public static final String COLUMN_NOMENT= "NOMENT";
    public static final String COLUMN_CVEEDO= "CVEEDO";
    public static final String COLUMN_NOMMUN= "NOMMUN";
    public static final String COLUMN_CVEMUN= "CVEMUN";
    public static final String COLUMN_LOCALI= "LOCALI";
    public static final String COLUMN_CVELOCA= "CVELOCA";
    public static final String COLUMN_PARNOM= "PARNOM";
    public static final String COLUMN_PARAPE= "PARAPE";
    public static final String COLUMN_PARAPEM= "PARAPEM";
    public static final String COLUMN_PARRAD1= "PARRAD1";
    public static final String COLUMN_EDAD= "EDAD";
    public static final String COLUMN_PARE6= "PARE6";
    public static final String COLUMN_PARE7= "PARE7";
    public static final String COLUMN_PARRAD2= "PARRAD2";
    public static final String COLUMN_PARRAD3= "PARRAD3";
    public static final String COLUMN_PARRAD4= "PARRAD4";
    public static final String COLUMN_PARRAD5= "PARRAD5";
    public static final String COLUMN_PARRAD6= "PARRAD6";
    public static final String COLUMN_PARRAD7= "PARRAD7";
    public static final String COLUMN_PARE8= "PARE8";
    public static final String COLUMN_PARE9= "PARE9";
    public static final String COLUMN_PARE10= "PARE10";
    public static final String COLUMN_PARE11= "PARE11";
    public static final String COLUMN_PARE12= "PARE12";
    public static final String COLUMN_PARE13= "PARE13";
    public static final String COLUMN_PARE14= "PARE14";
    public static final String COLUMN_PARE15= "PARE15";
    public static final String COLUMN_PAREO15= "PAREO15";
    public static final String COLUMN_PARE16= "PARE16";
    public static final String COLUMN_PARE17= "PARE17";
    public static final String COLUMN_PAREO17= "PAREO17";
    public static final String COLUMN_PARE18= "PARE18";
    public static final String COLUMN_PARE19= "PARE19";
    public static final String COLUMN_PARE20= "PARE20";
    public static final String COLUMN_PARE21= "PARE21";
    public static final String COLUMN_PARE22= "PARE22";
    public static final String COLUMN_PARE23= "PARE23";
    public static final String COLUMN_PARE24= "PARE24";
    public static final String COLUMN_PARE25= "PARE25";
    public static final String COLUMN_PARE26= "PARE26";
    public static final String COLUMN_PARE27= "PARE27";
    public static final String COLUMN_PARE28= "PARE28";
    public static final String COLUMN_PARE29= "PARE29";
    public static final String COLUMN_PARE30= "PARE30";
    public static final String COLUMN_PARE31= "PARE31";
    public static final String COLUMN_PARE32= "PARE32";
    public static final String COLUMN_PARE33= "PARE33";
    public static final String COLUMN_PARE34= "PARE34";
    public static final String COLUMN_PARE35= "PARE35";
    public static final String COLUMN_PARE36= "PARE36";
    public static final String COLUMN_PARE37= "PARE37";
    public static final String COLUMN_PARE38= "PARE38";
    public static final String COLUMN_PARE39= "PARE39";
    public static final String COLUMN_PARE40= "PARE40";
    public static final String COLUMN_PARE41= "PARE41";
    public static final String COLUMN_PARE42= "PARE42";
    public static final String COLUMN_PARE43= "PARE43";
    public static final String COLUMN_PARE44= "PARE44";
    public static final String COLUMN_PARE45= "PARE45";
    public static final String COLUMN_PARE46= "PARE46";
    public static final String COLUMN_PARE47= "PARE47";
    public static final String COLUMN_PARE48= "PARE48";
    public static final String COLUMN_PARE49= "PARE49";
    public static final String COLUMN_PARE50= "PARE50";
    public static final String COLUMN_PARE51= "PARE51";
    public static final String COLUMN_PARE52= "PARE52";
    public static final String COLUMN_PARE53= "PARE53";
    public static final String COLUMN_PARE54= "PARE54";
    public static final String COLUMN_PARE55= "PARE55";
    public static final String COLUMN_PARE56= "PARE56";
    public static final String COLUMN_PARE57= "PARE57";
    public static final String COLUMN_PARE58= "PARE58";
    public static final String COLUMN_PARE59= "PARE59";
    public static final String COLUMN_PARE60= "PARE60";
    public static final String COLUMN_PARE61= "PARE61";
    public static final String COLUMN_PARE62= "PARE62";
    public static final String COLUMN_PARE63= "PARE63";
    public static final String COLUMN_PARE64= "PARE64";
    public static final String COLUMN_PARE65= "PARE65";
    public static final String COLUMN_PARE66= "PARE66";
    public static final String COLUMN_PARE67= "PARE67";
    public static final String COLUMN_PARE68= "PARE68";
    public static final String COLUMN_PARE69= "PARE69";
    public static final String COLUMN_PARE70= "PARE70";
    public static final String COLUMN_PARE71= "PARE71";
    public static final String COLUMN_PARE72= "PARE72";
    public static final String COLUMN_PARE73= "PARE73";
    public static final String COLUMN_PARE74= "PARE74";
    public static final String COLUMN_PARE75= "PARE75";
    public static final String COLUMN_PARE76= "PARE76";
    public static final String COLUMN_PARE77= "PARE77";
    public static final String COLUMN_PARE78= "PARE78";
    public static final String COLUMN_PARE79= "PARE79";
    public static final String COLUMN_PARE80= "PARE80";
    public static final String COLUMN_PARE81= "PARE81";
    public static final String COLUMN_PARE82= "PARE82";
    public static final String COLUMN_PARE84= "PARE84";
    public static final String COLUMN_PARE85= "PARE85";
    public static final String COLUMN_PARE86= "PARE86";
    public static final String COLUMN_PARE87= "PARE87";
    public static final String COLUMN_PARE88= "PARE88";
    public static final String COLUMN_PARE89= "PARE89";
    public static final String COLUMN_PARE90= "PARE90";
    public static final String COLUMN_PARE91= "PARE91";
    public static final String COLUMN_PARE92= "PARE92";
    public static final String COLUMN_PARE93= "PARE93";
    public static final String COLUMN_PARE94= "PARE94";
    public static final String COLUMN_PARE95= "PARE95";
    public static final String COLUMN_PARE96= "PARE96";
    public static final String COLUMN_PARE97= "PARE97";
    public static final String COLUMN_PARE98= "PARE98";
    public static final String COLUMN_PARE99= "PARE99";
    public static final String COLUMN_PARE100= "PARE100";
    public static final String COLUMN_PARE101= "PARE101";
    public static final String COLUMN_PARE102= "PARE102";
    public static final String COLUMN_PARE103= "PARE103";
    public static final String COLUMN_PARE104= "PARE104";
    public static final String COLUMN_PARE105= "PARE105";
    public static final String COLUMN_PARE106= "PARE106";
    public static final String COLUMN_PARE107= "PARE107";
    public static final String COLUMN_PARE108= "PARE108";
    public static final String COLUMN_PARE109= "PARE109";
    public static final String COLUMN_PARE110= "PARE110";
    public static final String COLUMN_PARE111= "PARE111";
    public static final String COLUMN_PARE112= "PARE112";
    public static final String COLUMN_PARE113= "PARE113";
    public static final String COLUMN_PARE114= "PARE114";
    public static final String COLUMN_PARE115= "PARE115";
    public static final String COLUMN_PARE116= "PARE116";
    public static final String COLUMN_PARE117= "PARE117";
    public static final String COLUMN_PARE118= "PARE118";
    public static final String COLUMN_PARE119= "PARE119";
    public static final String COLUMN_PARE120= "PARE120";
    public static final String COLUMN_PARE121= "PARE121";
    public static final String COLUMN_PARE122= "PARE122";
    public static final String COLUMN_PARE123= "PARE123";
    public static final String COLUMN_PARE124= "PARE124";
    public static final String COLUMN_PARE125= "PARE125";
    public static final String COLUMN_PARE126= "PARE126";
    public static final String COLUMN_PARE127= "PARE127";
    public static final String COLUMN_PARE128= "PARE128";
    public static final String COLUMN_PARE129= "PARE129";
    public static final String COLUMN_PARE130= "PARE130";
    public static final String COLUMN_PARE131= "PARE131";
    public static final String COLUMN_PARE132= "PARE132";
    public static final String COLUMN_PARE133= "PARE133";
    public static final String COLUMN_PARE134= "PARE134";
    public static final String COLUMN_PARE135= "PARE135";
    public static final String COLUMN_PARE136= "PARE136";
    public static final String COLUMN_PARE137= "PARE137";
    public static final String COLUMN_PARE138= "PARE138";
    public static final String COLUMN_PARE139= "PARE139";
    public static final String COLUMN_PARE140= "PARE140";
    public static final String COLUMN_PARE141= "PARE141";
    public static final String COLUMN_PARE142= "PARE142";
    public static final String COLUMN_PARE143= "PARE143";
    public static final String COLUMN_PARE144= "PARE144";
    public static final String COLUMN_PARE145= "PARE145";
    public static final String COLUMN_PARE146= "PARE146";
    public static final String COLUMN_PARE147= "PARE147";
    public static final String COLUMN_PARE148= "PARE148";
    public static final String COLUMN_PARE149= "PARE149";
    public static final String COLUMN_PARE150= "PARE150";
    public static final String COLUMN_PARE151= "PARE151";
    public static final String COLUMN_PARE152= "PARE152";
    public static final String COLUMN_FOTO1 = "FOTO1";
    public static final String COLUMN_FOTO2 = "FOTO2";
    public static final String COLUMN_LONGITUD = "LONGITUD";
    public static final String COLUMN_LATITUD = "LATITUD";

    public static final String CREAR_TABLA_PAR_OPERATIVO= "CREATE TABLE " + TABLA_BD + "("
            + COLUMN_FOLIO + " VARCHAR PRIMARY KEY, "
            + COLUMN_FECHA + " VARCHAR, "
            + COLUMN_NOMENT + " VARCHAR, "
            + COLUMN_CVEEDO + " VARCHAR, "
            + COLUMN_NOMMUN + " VARCHAR, "
            + COLUMN_CVEMUN + " VARCHAR, "
            + COLUMN_LOCALI + " VARCHAR, "
            + COLUMN_CVELOCA + " VARCHAR, "

            + COLUMN_PARNOM + " VARCHAR, "
            + COLUMN_PARAPE + " VARCHAR, "
            + COLUMN_PARAPEM + " VARCHAR, "
            + COLUMN_PARRAD1 + " VARCHAR, "
            + COLUMN_EDAD + " VARCHAR, "
            + COLUMN_PARE6 + " VARCHAR, "
            + COLUMN_PARE7 + " VARCHAR, "
            + COLUMN_PARRAD2 + " VARCHAR, "
            + COLUMN_PARRAD3 + " VARCHAR, "
            + COLUMN_PARRAD4 + " VARCHAR, "
            + COLUMN_PARRAD5 + " VARCHAR, "
            + COLUMN_PARRAD6 + " VARCHAR, "
            + COLUMN_PARRAD7 + " VARCHAR, "
            + COLUMN_PARE8 + " VARCHAR, "
            + COLUMN_PARE9 + " VARCHAR, "
            + COLUMN_PARE10 + " VARCHAR, "
            + COLUMN_PARE11 + " VARCHAR, "
            + COLUMN_PARE12 + " VARCHAR, "
            + COLUMN_PARE13 + " VARCHAR, "
            + COLUMN_PARE14 + " VARCHAR, "
            + COLUMN_PARE15 + " VARCHAR, "
            + COLUMN_PAREO15 + " VARCHAR, "
            + COLUMN_PARE16 + " VARCHAR, "
            + COLUMN_PARE17 + " VARCHAR, "
            + COLUMN_PAREO17 + " VARCHAR, "
            + COLUMN_PARE18 + " VARCHAR, "
            + COLUMN_PARE19 + " VARCHAR, "
            + COLUMN_PARE20 + " VARCHAR, "
            + COLUMN_PARE21 + " VARCHAR, "
            + COLUMN_PARE22 + " VARCHAR, "
            + COLUMN_PARE23 + " VARCHAR, "
            + COLUMN_PARE24 + " VARCHAR, "
            + COLUMN_PARE25 + " VARCHAR, "
            + COLUMN_PARE26 + " VARCHAR, "
            + COLUMN_PARE27 + " VARCHAR, "
            + COLUMN_PARE28 + " VARCHAR, "
            + COLUMN_PARE29 + " VARCHAR, "
            + COLUMN_PARE30 + " VARCHAR, "
            + COLUMN_PARE31 + " VARCHAR, "
            + COLUMN_PARE32 + " VARCHAR, "
            + COLUMN_PARE33 + " VARCHAR, "
            + COLUMN_PARE34 + " VARCHAR, "
            + COLUMN_PARE35 + " VARCHAR, "
            + COLUMN_PARE36 + " VARCHAR, "
            + COLUMN_PARE37 + " VARCHAR, "
            + COLUMN_PARE38 + " VARCHAR, "
            + COLUMN_PARE39 + " VARCHAR, "
            + COLUMN_PARE40 + " VARCHAR, "
            + COLUMN_PARE41 + " VARCHAR, "
            + COLUMN_PARE42 + " VARCHAR, "
            + COLUMN_PARE43 + " VARCHAR, "
            + COLUMN_PARE44 + " VARCHAR, "
            + COLUMN_PARE45 + " VARCHAR, "
            + COLUMN_PARE46 + " VARCHAR, "
            + COLUMN_PARE47 + " VARCHAR, "
            + COLUMN_PARE48 + " VARCHAR, "
            + COLUMN_PARE49 + " VARCHAR, "
            + COLUMN_PARE50 + " VARCHAR, "
            + COLUMN_PARE51 + " VARCHAR, "
            + COLUMN_PARE52 + " VARCHAR, "
            + COLUMN_PARE53 + " VARCHAR, "
            + COLUMN_PARE54 + " VARCHAR, "
            + COLUMN_PARE55 + " VARCHAR, "
            + COLUMN_PARE56 + " VARCHAR, "
            + COLUMN_PARE57 + " VARCHAR, "
            + COLUMN_PARE58 + " VARCHAR, "
            + COLUMN_PARE59 + " VARCHAR, "
            + COLUMN_PARE60 + " VARCHAR, "
            + COLUMN_PARE61 + " VARCHAR, "
            + COLUMN_PARE62 + " VARCHAR, "
            + COLUMN_PARE63 + " VARCHAR, "
            + COLUMN_PARE64 + " VARCHAR, "
            + COLUMN_PARE65 + " VARCHAR, "
            + COLUMN_PARE66 + " VARCHAR, "
            + COLUMN_PARE67 + " VARCHAR, "
            + COLUMN_PARE68 + " VARCHAR, "
            + COLUMN_PARE69 + " VARCHAR, "
            + COLUMN_PARE70 + " VARCHAR, "
            + COLUMN_PARE71 + " VARCHAR, "
            + COLUMN_PARE72 + " VARCHAR, "
            + COLUMN_PARE73 + " VARCHAR, "
            + COLUMN_PARE74 + " VARCHAR, "
            + COLUMN_PARE75 + " VARCHAR, "
            + COLUMN_PARE76 + " VARCHAR, "
            + COLUMN_PARE77 + " VARCHAR, "
            + COLUMN_PARE78 + " VARCHAR, "
            + COLUMN_PARE79 + " VARCHAR, "
            + COLUMN_PARE80 + " VARCHAR, "
            + COLUMN_PARE81 + " VARCHAR, "
            + COLUMN_PARE82 + " VARCHAR, "
            + COLUMN_PARE84 + " VARCHAR, "
            + COLUMN_PARE85 + " VARCHAR, "
            + COLUMN_PARE86 + " VARCHAR, "
            + COLUMN_PARE87 + " VARCHAR, "
            + COLUMN_PARE88 + " VARCHAR, "
            + COLUMN_PARE89 + " VARCHAR, "
            + COLUMN_PARE90 + " VARCHAR, "
            + COLUMN_PARE91 + " VARCHAR, "
            + COLUMN_PARE92 + " VARCHAR, "
            + COLUMN_PARE93 + " VARCHAR, "
            + COLUMN_PARE94 + " VARCHAR, "
            + COLUMN_PARE95 + " VARCHAR, "
            + COLUMN_PARE96 + " VARCHAR, "
            + COLUMN_PARE97 + " VARCHAR, "
            + COLUMN_PARE98 + " VARCHAR, "
            + COLUMN_PARE99 + " VARCHAR, "
            + COLUMN_PARE100 + " VARCHAR, "
            + COLUMN_PARE101 + " VARCHAR, "
            + COLUMN_PARE102 + " VARCHAR, "
            + COLUMN_PARE103 + " VARCHAR, "
            + COLUMN_PARE104 + " VARCHAR, "
            + COLUMN_PARE105 + " VARCHAR, "
            + COLUMN_PARE106 + " VARCHAR, "
            + COLUMN_PARE107 + " VARCHAR, "
            + COLUMN_PARE108 + " VARCHAR, "
            + COLUMN_PARE109 + " VARCHAR, "
            + COLUMN_PARE110 + " VARCHAR, "
            + COLUMN_PARE111 + " VARCHAR, "
            + COLUMN_PARE112 + " VARCHAR, "
            + COLUMN_PARE113 + " VARCHAR, "
            + COLUMN_PARE114 + " VARCHAR, "
            + COLUMN_PARE115 + " VARCHAR, "
            + COLUMN_PARE116 + " VARCHAR, "
            + COLUMN_PARE117 + " VARCHAR, "
            + COLUMN_PARE118 + " VARCHAR, "
            + COLUMN_PARE119 + " VARCHAR, "
            + COLUMN_PARE120 + " VARCHAR, "
            + COLUMN_PARE121 + " VARCHAR, "
            + COLUMN_PARE122 + " VARCHAR, "
            + COLUMN_PARE123 + " VARCHAR, "
            + COLUMN_PARE124 + " VARCHAR, "
            + COLUMN_PARE125 + " VARCHAR, "
            + COLUMN_PARE126 + " VARCHAR, "
            + COLUMN_PARE127 + " VARCHAR, "
            + COLUMN_PARE128 + " VARCHAR, "
            + COLUMN_PARE129 + " VARCHAR, "
            + COLUMN_PARE130 + " VARCHAR, "
            + COLUMN_PARE131 + " VARCHAR, "
            + COLUMN_PARE132 + " VARCHAR, "
            + COLUMN_PARE133 + " VARCHAR, "
            + COLUMN_PARE134 + " VARCHAR, "
            + COLUMN_PARE135 + " VARCHAR, "
            + COLUMN_PARE136 + " VARCHAR, "
            + COLUMN_PARE137 + " VARCHAR, "
            + COLUMN_PARE138 + " VARCHAR, "
            + COLUMN_PARE139 + " VARCHAR, "
            + COLUMN_PARE140 + " VARCHAR, "
            + COLUMN_PARE141 + " VARCHAR, "
            + COLUMN_PARE142 + " VARCHAR, "
            + COLUMN_PARE143 + " VARCHAR, "
            + COLUMN_PARE144 + " VARCHAR, "
            + COLUMN_PARE145 + " VARCHAR, "
            + COLUMN_PARE146 + " VARCHAR, "
            + COLUMN_PARE147 + " VARCHAR, "
            + COLUMN_PARE148 + " VARCHAR, "
            + COLUMN_PARE149 + " VARCHAR, "
            + COLUMN_PARE150 + " VARCHAR, "
            + COLUMN_PARE151 + " VARCHAR, "
            + COLUMN_PARE152 + " VARCHAR, "
            + COLUMN_FOTO1 + " VARCHAR, "
            + COLUMN_FOTO2 + " VARCHAR, "
            + COLUMN_LONGITUD + " VARCHAR, "
            + COLUMN_LATITUD + " VARCHAR); ";

}